USE `smart_food_safety`;

CREATE TABLE IF NOT EXISTS `food_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  `parent_id` BIGINT DEFAULT NULL COMMENT '父分类ID',
  `category_code` VARCHAR(64) NOT NULL COMMENT '分类编码',
  `category_name` VARCHAR(100) NOT NULL COMMENT '分类名称',
  `category_level` TINYINT NOT NULL COMMENT '分类层级：1/2',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
  `source_file` VARCHAR(255) DEFAULT NULL COMMENT '来源文件',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_food_category_code` (`category_code`),
  KEY `idx_food_category_parent` (`parent_id`),
  KEY `idx_food_category_level` (`category_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='标准食品分类表';

CREATE TABLE IF NOT EXISTS `food_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '标准食品ID',
  `food_code` VARCHAR(32) NOT NULL COMMENT '标准食品编码',
  `food_name` VARCHAR(150) NOT NULL COMMENT '标准食品名称',
  `category_level1_id` BIGINT DEFAULT NULL COMMENT '一级分类ID',
  `category_level2_id` BIGINT DEFAULT NULL COMMENT '二级分类ID',
  `edible_ratio` DECIMAL(5,2) DEFAULT NULL COMMENT '可食部比例',
  `energy_kcal` DECIMAL(10,2) DEFAULT NULL COMMENT '热量（千卡/100g）',
  `protein` DECIMAL(10,2) DEFAULT NULL COMMENT '蛋白质（g/100g）',
  `fat` DECIMAL(10,2) DEFAULT NULL COMMENT '脂肪（g/100g）',
  `carbohydrate` DECIMAL(10,2) DEFAULT NULL COMMENT '碳水化合物（g/100g）',
  `dietary_fiber` DECIMAL(10,2) DEFAULT NULL COMMENT '膳食纤维（g/100g）',
  `sodium` DECIMAL(10,2) DEFAULT NULL COMMENT '钠（mg/100g）',
  `vitamin_a` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素A（ug/100g）',
  `vitamin_b1` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素B1（mg/100g）',
  `vitamin_b2` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素B2（mg/100g）',
  `vitamin_c` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素C（mg/100g）',
  `vitamin_e` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素E（mg/100g）',
  `calcium` DECIMAL(10,2) DEFAULT NULL COMMENT '钙（mg/100g）',
  `iron` DECIMAL(10,2) DEFAULT NULL COMMENT '铁（mg/100g）',
  `zinc` DECIMAL(10,2) DEFAULT NULL COMMENT '锌（mg/100g）',
  `source_file` VARCHAR(255) DEFAULT NULL COMMENT '来源文件',
  `source_version` VARCHAR(100) DEFAULT NULL COMMENT '来源版本',
  `raw_payload` JSON DEFAULT NULL COMMENT '原始JSON快照',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_food_item_code` (`food_code`),
  KEY `idx_food_item_level1` (`category_level1_id`),
  KEY `idx_food_item_level2` (`category_level2_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='标准食品主表';

CREATE TABLE IF NOT EXISTS `material_food_mapping` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '映射ID',
  `material_id` BIGINT NOT NULL COMMENT '业务物料ID',
  `food_item_id` BIGINT NOT NULL COMMENT '标准食品ID',
  `match_status` VARCHAR(20) NOT NULL DEFAULT 'confirmed' COMMENT '映射状态',
  `confirmed_by` BIGINT DEFAULT NULL COMMENT '确认人',
  `confirmed_at` DATETIME DEFAULT NULL COMMENT '确认时间',
  `remark` VARCHAR(300) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_material_food_mapping` (`material_id`),
  KEY `idx_material_food_food_item` (`food_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务物料-标准食品映射表';

CREATE TABLE IF NOT EXISTS `recipe_nutrition_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '结果ID',
  `recipe_id` BIGINT NOT NULL COMMENT '菜谱ID',
  `calc_version` INT NOT NULL DEFAULT 1 COMMENT '计算版本',
  `calories` DECIMAL(10,2) DEFAULT NULL COMMENT '热量',
  `protein` DECIMAL(10,2) DEFAULT NULL COMMENT '蛋白质',
  `carbohydrate` DECIMAL(10,2) DEFAULT NULL COMMENT '碳水',
  `fat` DECIMAL(10,2) DEFAULT NULL COMMENT '脂肪',
  `sodium` DECIMAL(10,2) DEFAULT NULL COMMENT '钠',
  `fiber` DECIMAL(10,2) DEFAULT NULL COMMENT '膳食纤维',
  `vitamin_a` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素A',
  `vitamin_b1` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素B1',
  `vitamin_b2` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素B2',
  `vitamin_c` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素C',
  `vitamin_d` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素D',
  `vitamin_e` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素E',
  `calcium` DECIMAL(10,2) DEFAULT NULL COMMENT '钙',
  `iron` DECIMAL(10,2) DEFAULT NULL COMMENT '铁',
  `zinc` DECIMAL(10,2) DEFAULT NULL COMMENT '锌',
  `nutrition_score` INT DEFAULT NULL COMMENT '营养评分',
  `pass_status` VARCHAR(20) DEFAULT NULL COMMENT '达标状态',
  `data_completeness` DECIMAL(5,2) DEFAULT NULL COMMENT '数据完整度',
  `missing_material_count` INT NOT NULL DEFAULT 0 COMMENT '缺失物料数',
  `missing_materials` TEXT DEFAULT NULL COMMENT '缺失物料列表',
  `calculated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '计算时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_recipe_nutrition_result_recipe` (`recipe_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='菜谱营养计算结果表';

ALTER TABLE `wms_material`
  ADD COLUMN IF NOT EXISTS `food_item_id` BIGINT DEFAULT NULL COMMENT '关联标准食品ID' AFTER `material_category`,
  ADD COLUMN IF NOT EXISTS `calories` DECIMAL(10,2) DEFAULT NULL COMMENT '热量（千卡/100g）' AFTER `remark`,
  ADD COLUMN IF NOT EXISTS `protein` DECIMAL(10,2) DEFAULT NULL COMMENT '蛋白质（g/100g）' AFTER `calories`,
  ADD COLUMN IF NOT EXISTS `carbohydrate` DECIMAL(10,2) DEFAULT NULL COMMENT '碳水化合物（g/100g）' AFTER `protein`,
  ADD COLUMN IF NOT EXISTS `fat` DECIMAL(10,2) DEFAULT NULL COMMENT '脂肪（g/100g）' AFTER `carbohydrate`,
  ADD COLUMN IF NOT EXISTS `sodium` DECIMAL(10,2) DEFAULT NULL COMMENT '钠（mg/100g）' AFTER `fat`,
  ADD COLUMN IF NOT EXISTS `fiber` DECIMAL(10,2) DEFAULT NULL COMMENT '膳食纤维（g/100g）' AFTER `sodium`,
  ADD COLUMN IF NOT EXISTS `vitamin_a` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素A（ug/100g）' AFTER `fiber`,
  ADD COLUMN IF NOT EXISTS `vitamin_b1` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素B1（mg/100g）' AFTER `vitamin_a`,
  ADD COLUMN IF NOT EXISTS `vitamin_b2` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素B2（mg/100g）' AFTER `vitamin_b1`,
  ADD COLUMN IF NOT EXISTS `vitamin_c` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素C（mg/100g）' AFTER `vitamin_b2`,
  ADD COLUMN IF NOT EXISTS `vitamin_e` DECIMAL(10,2) DEFAULT NULL COMMENT '维生素E（mg/100g）' AFTER `vitamin_c`,
  ADD COLUMN IF NOT EXISTS `calcium` DECIMAL(10,2) DEFAULT NULL COMMENT '钙（mg/100g）' AFTER `vitamin_e`,
  ADD COLUMN IF NOT EXISTS `iron` DECIMAL(10,2) DEFAULT NULL COMMENT '铁（mg/100g）' AFTER `calcium`,
  ADD COLUMN IF NOT EXISTS `zinc` DECIMAL(10,2) DEFAULT NULL COMMENT '锌（mg/100g）' AFTER `iron`,
  ADD COLUMN IF NOT EXISTS `nutrition_source_type` VARCHAR(30) DEFAULT NULL COMMENT '营养来源类型' AFTER `zinc`,
  ADD COLUMN IF NOT EXISTS `nutrition_source_ref_id` BIGINT DEFAULT NULL COMMENT '营养来源引用ID' AFTER `nutrition_source_type`,
  ADD COLUMN IF NOT EXISTS `nutrition_synced_at` DATETIME DEFAULT NULL COMMENT '营养同步时间' AFTER `nutrition_source_ref_id`;
