CREATE TABLE IF NOT EXISTS `sys_ai_service_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(50) NOT NULL,
  `service_type` VARCHAR(20) NOT NULL COMMENT 'text/vision',
  `base_url` VARCHAR(255) NOT NULL,
  `api_key_encrypted` VARCHAR(1024) NOT NULL,
  `model_name` VARCHAR(100) NOT NULL,
  `applicable_modules` JSON NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'inactive',
  `last_test_status` VARCHAR(20) DEFAULT NULL,
  `last_test_message` VARCHAR(500) DEFAULT NULL,
  `last_test_at` DATETIME DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `org_id` BIGINT DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 1,
  `created_by` BIGINT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_service_name` (`service_name`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_ai_service_type_status` (`service_type`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI服务配置表';

CREATE TABLE IF NOT EXISTS `sys_ai_request_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `service_config_id` BIGINT NOT NULL,
  `request_type` VARCHAR(30) NOT NULL COMMENT 'test/business',
  `service_type` VARCHAR(20) NOT NULL,
  `module_code` VARCHAR(50) NOT NULL,
  `model_name` VARCHAR(100) DEFAULT NULL,
  `request_summary` VARCHAR(500) DEFAULT NULL,
  `response_summary` VARCHAR(500) DEFAULT NULL,
  `target_url` VARCHAR(255) DEFAULT NULL,
  `duration_ms` INT DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL,
  `error_message` VARCHAR(500) DEFAULT NULL,
  `org_id` BIGINT DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 1,
  `created_by` BIGINT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ai_request_service` (`service_config_id`),
  KEY `idx_ai_request_module` (`module_code`),
  KEY `idx_ai_request_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI请求日志表';

CREATE TABLE IF NOT EXISTS `device_vision_analysis_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `screenshot_id` BIGINT NOT NULL,
  `recording_id` BIGINT DEFAULT NULL,
  `device_id` BIGINT DEFAULT NULL,
  `device_name` VARCHAR(100) DEFAULT NULL,
  `org_id` BIGINT DEFAULT 0,
  `task_status` VARCHAR(30) NOT NULL COMMENT 'processing/alerted/threshold_not_met/failed',
  `violation_type` VARCHAR(30) DEFAULT NULL,
  `confidence` INT DEFAULT NULL,
  `summary` VARCHAR(500) DEFAULT NULL,
  `model_version` VARCHAR(100) DEFAULT NULL,
  `raw_response` JSON DEFAULT NULL,
  `alert_id` BIGINT DEFAULT NULL,
  `error_message` VARCHAR(500) DEFAULT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 1,
  `created_by` BIGINT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_vision_task_screenshot` (`screenshot_id`),
  KEY `idx_vision_task_status` (`task_status`),
  KEY `idx_vision_task_alert` (`alert_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='视觉分析任务表';
