-- ============================================================
-- 智慧厨房管理平台 - 数据库初始化脚本（第二部分）
-- 采购管理模块（scm_）
-- ============================================================

USE `smart_food_safety`;

-- ---------------------------
-- 3.1 供应商表（scm_supplier）
-- ---------------------------
DROP TABLE IF EXISTS `scm_supplier`;
CREATE TABLE `scm_supplier` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '供应商ID',
  `supplier_code` VARCHAR(50) NOT NULL COMMENT '供应商编码',
  `supplier_name` VARCHAR(100) NOT NULL COMMENT '供应商名称',
  `contact_name` VARCHAR(50) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
  `address` VARCHAR(200) DEFAULT NULL COMMENT '地址',
  `supplier_type` VARCHAR(50) DEFAULT NULL COMMENT '供应商类型（如蔬菜/肉类/粮油）',
  `unified_credit_code` VARCHAR(50) DEFAULT NULL COMMENT '统一社会信用代码',
  `bank_account` VARCHAR(50) DEFAULT NULL COMMENT '银行账号',
  `bank_name` VARCHAR(100) DEFAULT NULL COMMENT '开户行',
  `category_tags` VARCHAR(500) DEFAULT NULL COMMENT '供应品类标签（JSON数组，如["蔬菜","肉类"]）',
  `license_no` VARCHAR(100) DEFAULT NULL COMMENT '营业执照编号',
  `license_expires_at` DATETIME DEFAULT NULL COMMENT '营业执照到期日',
  `food_license_no` VARCHAR(100) DEFAULT NULL COMMENT '食品经营许可证编号',
  `food_license_expires_at` DATETIME DEFAULT NULL COMMENT '食品许可证到期日',
  `qualification_files` JSON DEFAULT NULL COMMENT '资质文件列表（JSON数组，如[{\"id\":1,\"name\":\"a.pdf\",\"size\":\"12 KB\"}]）',
  `credit_score` DECIMAL(5,2) DEFAULT 100.00 COMMENT '信用评分（0-100）',
  `score_qualification` DECIMAL(5,2) DEFAULT NULL COMMENT '资质完整性评分',
  `score_quality` DECIMAL(5,2) DEFAULT NULL COMMENT '历史供货质量评分',
  `score_price` DECIMAL(5,2) DEFAULT NULL COMMENT '价格稳定性评分',
  `score_delivery` DECIMAL(5,2) DEFAULT NULL COMMENT '履约准时率评分',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '状态：pending=待审核，active=已审核，rejected=已驳回，disabled=禁用，cancelled=注销',
  `disable_reason` VARCHAR(500) DEFAULT NULL COMMENT '禁用原因',
  `cancel_reason` VARCHAR(500) DEFAULT NULL COMMENT '注销原因',
  `audit_by` BIGINT DEFAULT NULL COMMENT '审核人ID',
  `audit_at` DATETIME DEFAULT NULL COMMENT '审核时间',
  `audit_remark` VARCHAR(500) DEFAULT NULL COMMENT '审核备注',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_supplier_code` (`tenant_id`, `supplier_code`, (CASE WHEN `deleted` = 0 THEN 0 ELSE NULL END)) COMMENT '租户+供应商编码软删除唯一约束',
  UNIQUE KEY `uk_tenant_supplier_name` (`tenant_id`, `supplier_name`, (CASE WHEN `deleted` = 0 THEN 0 ELSE NULL END)) COMMENT '租户+供应商名称软删除唯一约束',
  UNIQUE KEY `uk_tenant_business_license_no` (`tenant_id`, `license_no`, (CASE WHEN `deleted` = 0 THEN 0 ELSE NULL END)) COMMENT '租户+营业执照编号软删除条件唯一约束',
  UNIQUE KEY `uk_tenant_food_license_no` (`tenant_id`, `food_license_no`, (CASE WHEN `deleted` = 0 THEN 0 ELSE NULL END)) COMMENT '租户+食品许可证号软删除条件唯一约束',
  KEY `idx_supplier_status` (`status`),
  KEY `idx_supplier_org` (`org_id`),
  KEY `idx_supplier_tenant` (`tenant_id`),
  KEY `idx_supplier_license_expires` (`license_expires_at`),
  KEY `idx_supplier_food_license_expires` (`food_license_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商表';

-- ---------------------------
-- 3.2 采购计划表（scm_purchase_plan）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_plan`;
CREATE TABLE `scm_purchase_plan` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '计划ID',
  `plan_no` VARCHAR(50) NOT NULL COMMENT '计划编号（系统生成）',
  `plan_name` VARCHAR(100) DEFAULT NULL COMMENT '计划名称',
  `plan_date` DATE NOT NULL COMMENT '计划采购日期',
  `source_type` VARCHAR(20) NOT NULL DEFAULT 'manual' COMMENT '来源类型：manual=手动，ai_predict=AI预测，stock_alert=库存预警',
  `source_ref_id` BIGINT DEFAULT NULL COMMENT '来源单据ID（如预警单ID）',
  `budget_amount` DECIMAL(12,2) DEFAULT 0.00 COMMENT '预算金额',
  `total_amount` DECIMAL(12,2) DEFAULT 0.00 COMMENT '计划总金额',
  `related_document` VARCHAR(200) DEFAULT NULL COMMENT '关联单据展示值',
  `attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '附件名称',
  `attachment_url` VARCHAR(1000) DEFAULT NULL COMMENT '附件地址',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `status` VARCHAR(20) NOT NULL DEFAULT 'draft' COMMENT '状态：draft=草稿，pending=待审核，approved=已审核，rejected=已驳回，pending_void_approve=待作废审核，voided=已作废',
  `submitted_at` DATETIME DEFAULT NULL COMMENT '提交时间',
  `approved_by` BIGINT DEFAULT NULL COMMENT '审核人ID',
  `approved_at` DATETIME DEFAULT NULL COMMENT '审核时间',
  `approve_remark` VARCHAR(500) DEFAULT NULL COMMENT '审批备注',
  `void_origin_status` VARCHAR(20) DEFAULT NULL COMMENT '发起作废前原始状态：approved=已审核，rejected=已驳回',
  `void_reason` VARCHAR(500) DEFAULT NULL COMMENT '作废原因',
  `void_requested_by` BIGINT DEFAULT NULL COMMENT '作废申请人ID',
  `void_requested_at` DATETIME DEFAULT NULL COMMENT '作废申请时间',
  `void_audit_by` BIGINT DEFAULT NULL COMMENT '作废审核人ID',
  `void_audit_at` DATETIME DEFAULT NULL COMMENT '作废审核时间',
  `void_audit_remark` VARCHAR(500) DEFAULT NULL COMMENT '作废审核意见',
  `merge_locked` TINYINT NOT NULL DEFAULT 0 COMMENT '是否被多选合并生成采购订单占用：0=否，1=是',
  `merge_order_id` BIGINT DEFAULT NULL COMMENT '多选合并生成关联采购订单ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_no` (`plan_no`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_plan_status` (`status`),
  KEY `idx_plan_date` (`plan_date`),
  KEY `idx_plan_org` (`org_id`),
  KEY `idx_plan_tenant` (`tenant_id`),
  KEY `idx_plan_created_at` (`created_at`),
  KEY `idx_plan_merge_order` (`merge_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购计划表';

-- ---------------------------
-- 3.3 采购计划附件表（scm_purchase_plan_attachment）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_plan_attachment`;
CREATE TABLE `scm_purchase_plan_attachment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `plan_id` BIGINT NOT NULL COMMENT '采购计划ID',
  `file_name` VARCHAR(255) NOT NULL COMMENT '附件名称',
  `file_size` VARCHAR(30) DEFAULT NULL COMMENT '附件大小',
  `file_url` VARCHAR(1000) NOT NULL COMMENT '附件地址',
  `sort_order` INT NOT NULL DEFAULT 1 COMMENT '排序',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_plan_attachment_plan` (`plan_id`),
  KEY `idx_plan_attachment_org` (`org_id`),
  KEY `idx_plan_attachment_tenant` (`tenant_id`),
  KEY `idx_plan_attachment_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购计划附件表';

-- ---------------------------
-- 3.4 采购计划明细表（scm_purchase_plan_item）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_plan_item`;
CREATE TABLE `scm_purchase_plan_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '明细ID',
  `plan_id` BIGINT NOT NULL COMMENT '采购计划ID',
  `material_id` BIGINT NOT NULL COMMENT '物料ID',
  `material_name` VARCHAR(100) NOT NULL COMMENT '物料名称（冗余）',
  `material_spec` VARCHAR(100) DEFAULT NULL COMMENT '规格（冗余）',
  `material_unit` VARCHAR(20) NOT NULL COMMENT '单位（冗余）',
  `plan_qty` DECIMAL(10,3) NOT NULL COMMENT '计划数量',
  `estimate_price` DECIMAL(10,2) DEFAULT NULL COMMENT '预估单价',
  `estimate_amount` DECIMAL(12,2) DEFAULT NULL COMMENT '预估金额',
  `remark` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_plan_item_plan` (`plan_id`),
  KEY `idx_plan_item_material` (`material_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购计划明细表';

-- ---------------------------
-- 3.5 采购需求预测主表（scm_purchase_demand_forecast）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_demand_forecast`;
CREATE TABLE `scm_purchase_demand_forecast` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '预测单ID',
  `forecast_no` VARCHAR(50) NOT NULL COMMENT '预测单号',
  `forecast_name` VARCHAR(100) DEFAULT NULL COMMENT '预测名称',
  `forecast_dimension` VARCHAR(20) NOT NULL COMMENT '预测维度：daily=日，weekly=周',
  `forecast_days` INT NOT NULL DEFAULT 7 COMMENT '预测周期天数',
  `basis_date` DATE NOT NULL COMMENT '预测基准日期',
  `horizon_start_date` DATE NOT NULL COMMENT '预测周期开始日期',
  `horizon_end_date` DATE NOT NULL COMMENT '预测周期结束日期',
  `material_count` INT NOT NULL DEFAULT 0 COMMENT '预测物料数',
  `total_suggested_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '建议采购总金额',
  `calendar_factor` DECIMAL(6,3) NOT NULL DEFAULT 1.000 COMMENT '单位日历因子',
  `holiday_factor` DECIMAL(6,3) NOT NULL DEFAULT 1.000 COMMENT '节假日因子',
  `activity_factor` DECIMAL(6,3) NOT NULL DEFAULT 1.000 COMMENT '活动因子',
  `summary_basis` VARCHAR(1000) DEFAULT NULL COMMENT '预测摘要依据',
  `evaluation_status` VARCHAR(20) DEFAULT 'pending' COMMENT '评估状态：pending=待回算，completed=已回算',
  `evaluated_at` DATETIME DEFAULT NULL COMMENT '回算完成时间',
  `overall_wape` DECIMAL(12,6) DEFAULT NULL COMMENT '整体WAPE',
  `overall_mape` DECIMAL(12,6) DEFAULT NULL COMMENT '整体MAPE',
  `overall_rmse` DECIMAL(12,6) DEFAULT NULL COMMENT '整体RMSE',
  `bias_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '整体偏差率',
  `stockout_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '缺货率',
  `oversupply_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '过采率',
  `optimization_version` INT NOT NULL DEFAULT 0 COMMENT '自动优化版本号',
  `optimization_score` DECIMAL(12,6) DEFAULT NULL COMMENT '自动优化评分',
  `explanation_summary` VARCHAR(1000) DEFAULT NULL COMMENT '解释摘要',
  `approval_summary` VARCHAR(1000) DEFAULT NULL COMMENT '审批说明摘要',
  `reorder_triggered_count` INT NOT NULL DEFAULT 0 COMMENT '触发订货点物料数',
  `risk_item_count` INT NOT NULL DEFAULT 0 COMMENT '风险物料数',
  `supplier_recommended_count` INT NOT NULL DEFAULT 0 COMMENT '已推荐供应商物料数',
  `manual_review_count` INT NOT NULL DEFAULT 0 COMMENT '建议人工复核物料数',
  `warning_item_count` INT NOT NULL DEFAULT 0 COMMENT '触发预警物料数',
  `total_optimization_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '综合优化成本',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_forecast_no` (`forecast_no`),
  KEY `idx_forecast_org` (`org_id`),
  KEY `idx_forecast_created_at` (`created_at`),
  KEY `idx_forecast_dimension` (`forecast_dimension`),
  KEY `idx_forecast_eval_status` (`evaluation_status`, `horizon_end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购需求预测主表';

-- ---------------------------
-- 3.6 采购需求预测明细表（scm_purchase_demand_forecast_item）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_demand_forecast_item`;
CREATE TABLE `scm_purchase_demand_forecast_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '预测明细ID',
  `forecast_id` BIGINT NOT NULL COMMENT '预测单ID',
  `material_id` BIGINT NOT NULL COMMENT '物料ID',
  `material_name` VARCHAR(100) NOT NULL COMMENT '物料名称',
  `material_spec` VARCHAR(100) DEFAULT NULL COMMENT '规格',
  `material_unit` VARCHAR(20) DEFAULT NULL COMMENT '单位',
  `current_inventory_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '当前库存',
  `historical_plan_avg_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '近30天计划日均量',
  `historical_order_avg_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '近30天订单日均量',
  `recipe_demand_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '未来7天菜谱需求量',
  `forecast_demand_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '预测需求量',
  `safety_stock_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '安全库存',
  `avg_daily_demand_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '日均需求量',
  `review_period_days` INT DEFAULT NULL COMMENT '评审周期天数',
  `reorder_point_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '订货点',
  `target_stock_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '目标库存上限',
  `inventory_position_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '库存位置量',
  `theoretical_suggested_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '理论建议采购量',
  `suggested_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '建议采购量',
  `confidence_lower_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '置信区间下限',
  `confidence_upper_qty` DECIMAL(10,3) NOT NULL DEFAULT 0.000 COMMENT '置信区间上限',
  `estimated_unit_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '预估单价',
  `estimated_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '预估金额',
  `replenishment_priority` VARCHAR(20) DEFAULT NULL COMMENT '补货优先级',
  `model_type` VARCHAR(50) DEFAULT NULL COMMENT '模型类型',
  `material_segment` VARCHAR(50) DEFAULT NULL COMMENT '物料分层',
  `forecast_basis` VARCHAR(1000) DEFAULT NULL COMMENT '预测依据',
  `explanation_summary` VARCHAR(500) DEFAULT NULL COMMENT '解释摘要',
  `explanation_detail` VARCHAR(2000) DEFAULT NULL COMMENT '解释详情',
  `explanation_template_code` VARCHAR(50) DEFAULT NULL COMMENT '解释模板编码',
  `explanation_title` VARCHAR(120) DEFAULT NULL COMMENT '解释标题',
  `warning_level` VARCHAR(20) DEFAULT NULL COMMENT '预警级别',
  `warning_message` VARCHAR(500) DEFAULT NULL COMMENT '预警说明',
  `approval_note` VARCHAR(500) DEFAULT NULL COMMENT '审批说明',
  `manual_review_required` TINYINT NOT NULL DEFAULT 0 COMMENT '是否建议人工复核',
  `explanation_factors_json` TEXT DEFAULT NULL COMMENT '解释证据JSON',
  `anomaly_codes` VARCHAR(500) DEFAULT NULL COMMENT '异常编码',
  `explanation_sort_score` DECIMAL(12,6) DEFAULT NULL COMMENT '解释排序分',
  `anomaly_flags` VARCHAR(1000) DEFAULT NULL COMMENT '异常标签',
  `actual_consumption_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '实际消耗量',
  `abs_error` DECIMAL(10,3) DEFAULT NULL COMMENT '绝对误差',
  `ape` DECIMAL(12,6) DEFAULT NULL COMMENT '绝对百分比误差',
  `rmse` DECIMAL(12,6) DEFAULT NULL COMMENT '均方根误差',
  `bias_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '偏差量',
  `recipe_drive_ratio` DECIMAL(12,6) DEFAULT NULL COMMENT '菜谱驱动占比',
  `demand_active_ratio` DECIMAL(12,6) DEFAULT NULL COMMENT '需求活跃度',
  `demand_cv` DECIMAL(12,6) DEFAULT NULL COMMENT '需求波动系数',
  `activity_sensitivity` DECIMAL(12,6) DEFAULT NULL COMMENT '活动敏感度',
  `service_level` DECIMAL(12,6) DEFAULT NULL COMMENT '服务水平',
  `lead_time_days` INT DEFAULT NULL COMMENT '提前期天数',
  `effective_lead_time_days` DECIMAL(12,6) DEFAULT NULL COMMENT '有效提前期天数',
  `min_order_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '最小起订量',
  `pack_size` DECIMAL(10,3) DEFAULT NULL COMMENT '包装规格',
  `max_allowed_stock_qty` DECIMAL(10,3) DEFAULT NULL COMMENT '最大允许库存',
  `max_coverage_days` INT DEFAULT NULL COMMENT '最大覆盖天数',
  `recommended_supplier_id` BIGINT DEFAULT NULL COMMENT '推荐供应商ID',
  `recommended_supplier_name` VARCHAR(100) DEFAULT NULL COMMENT '推荐供应商名称',
  `supplier_score` DECIMAL(12,6) DEFAULT NULL COMMENT '供应商综合评分',
  `supplier_fill_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '供应商履约率',
  `supplier_on_time_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '供应商准时率',
  `order_now` TINYINT NOT NULL DEFAULT 0 COMMENT '是否建议立即下单',
  `order_action` VARCHAR(20) DEFAULT NULL COMMENT '下单动作建议',
  `shortage_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '缺货成本',
  `holding_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '库存持有成本',
  `expiry_risk_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '临期报废成本',
  `order_processing_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '下单成本',
  `purchase_price_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '采购价格成本',
  `total_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '综合优化成本',
  `phase_three_risk_flags` VARCHAR(1000) DEFAULT NULL COMMENT '三期风险标记',
  `evaluation_status` VARCHAR(20) DEFAULT 'pending' COMMENT '评估状态',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_forecast_item_forecast` (`forecast_id`),
  KEY `idx_forecast_item_material` (`material_id`),
  KEY `idx_forecast_item_org` (`org_id`),
  KEY `idx_forecast_item_segment` (`material_segment`, `model_type`),
  KEY `idx_forecast_item_supplier` (`recommended_supplier_id`),
  KEY `idx_forecast_item_order_now` (`order_now`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购需求预测明细表';

-- ---------------------------
-- 3.6.1 物料日消耗事实表（scm_material_daily_consumption）
-- ---------------------------
DROP TABLE IF EXISTS `scm_material_daily_consumption`;
CREATE TABLE `scm_material_daily_consumption` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `stat_date` DATE NOT NULL COMMENT '统计日期',
  `material_id` BIGINT NOT NULL COMMENT '物料ID',
  `opening_stock_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '期初库存',
  `inbound_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '当日入库量',
  `outbound_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '当日出库量',
  `adjustment_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '库存调整量',
  `closing_stock_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '期末库存',
  `consumed_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '实际消耗量',
  `data_source` VARCHAR(50) DEFAULT NULL COMMENT '计算来源',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_consumption_org_date_material` (`org_id`, `tenant_id`, `stat_date`, `material_id`),
  KEY `idx_consumption_org_date_material` (`org_id`, `stat_date`, `material_id`),
  KEY `idx_consumption_material_date` (`material_id`, `stat_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料日消耗事实表';

-- ---------------------------
-- 3.6.2 菜谱物料日需求展开表（scm_recipe_material_daily_demand）
-- ---------------------------
DROP TABLE IF EXISTS `scm_recipe_material_daily_demand`;
CREATE TABLE `scm_recipe_material_daily_demand` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `demand_date` DATE NOT NULL COMMENT '需求日期',
  `recipe_plan_id` BIGINT NOT NULL COMMENT '菜谱计划ID',
  `recipe_id` BIGINT NOT NULL COMMENT '菜谱ID',
  `material_id` BIGINT NOT NULL COMMENT '物料ID',
  `servings` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '计划份数',
  `standard_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '单份标准用量',
  `loss_rate` DECIMAL(8,4) NOT NULL DEFAULT 0.0000 COMMENT '损耗率',
  `theoretical_demand_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '理论需求量',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_recipe_demand_org_plan_material` (`org_id`, `tenant_id`, `demand_date`, `recipe_plan_id`, `recipe_id`, `material_id`),
  KEY `idx_recipe_demand_org_date_material` (`org_id`, `demand_date`, `material_id`),
  KEY `idx_recipe_demand_plan` (`recipe_plan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='菜谱物料日需求展开表';

-- ---------------------------
-- 3.6.3 物料日特征宽表（scm_material_daily_feature）
-- ---------------------------
DROP TABLE IF EXISTS `scm_material_daily_feature`;
CREATE TABLE `scm_material_daily_feature` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `stat_date` DATE NOT NULL COMMENT '特征日期',
  `material_id` BIGINT NOT NULL COMMENT '物料ID',
  `current_stock_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '当前库存',
  `available_stock_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '当前可用库存',
  `avg_consumption_7d` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '近7日均耗',
  `avg_consumption_14d` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '近14日均耗',
  `avg_consumption_30d` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '近30日均耗',
  `std_consumption_30d` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '近30日消耗标准差',
  `recipe_demand_7d` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '未来7天菜谱需求',
  `recipe_history_30d` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '近30天理论菜谱需求',
  `actual_consumption_30d` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '近30天实际消耗',
  `consumption_days_30d` INT NOT NULL DEFAULT 0 COMMENT '近30天有消耗天数',
  `inventory_turnover_days` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '库存周转天数',
  `pending_plan_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '待执行采购计划量',
  `in_transit_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '在途采购量',
  `holiday_factor` DECIMAL(8,4) NOT NULL DEFAULT 1.0000 COMMENT '节假日系数',
  `activity_factor` DECIMAL(8,4) NOT NULL DEFAULT 1.0000 COMMENT '活动系数',
  `material_category` VARCHAR(50) DEFAULT NULL COMMENT '物料类别',
  `forecast_type` VARCHAR(50) DEFAULT NULL COMMENT '预测算法类型',
  `recipe_drive_ratio` DECIMAL(12,6) DEFAULT NULL COMMENT '菜谱驱动占比',
  `demand_active_ratio` DECIMAL(12,6) DEFAULT NULL COMMENT '需求活跃度',
  `demand_cv` DECIMAL(12,6) DEFAULT NULL COMMENT '需求波动系数',
  `activity_sensitivity` DECIMAL(12,6) DEFAULT NULL COMMENT '活动敏感度',
  `material_segment` VARCHAR(50) DEFAULT NULL COMMENT '物料分层',
  `lead_time_days` INT DEFAULT NULL COMMENT '提前期天数',
  `service_level` DECIMAL(12,6) DEFAULT NULL COMMENT '服务水平',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_feature_org_date_material` (`org_id`, `tenant_id`, `stat_date`, `material_id`),
  KEY `idx_feature_org_date_material` (`org_id`, `stat_date`, `material_id`),
  KEY `idx_feature_segment` (`org_id`, `stat_date`, `material_segment`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料日特征宽表';

-- ---------------------------
-- 3.6.4 采购需求预测任务主表（scm_purchase_demand_forecast_task）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_demand_forecast_task`;
CREATE TABLE `scm_purchase_demand_forecast_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `forecast_no` VARCHAR(50) NOT NULL COMMENT '预测单号',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `horizon_type` VARCHAR(20) NOT NULL COMMENT '预测维度',
  `horizon_start_date` DATE NOT NULL COMMENT '预测开始日期',
  `horizon_end_date` DATE NOT NULL COMMENT '预测结束日期',
  `task_status` VARCHAR(20) NOT NULL COMMENT '任务状态',
  `material_count` INT NOT NULL DEFAULT 0 COMMENT '预测物料数',
  `trigger_type` VARCHAR(20) NOT NULL DEFAULT 'manual' COMMENT '触发类型',
  `evaluation_status` VARCHAR(20) DEFAULT 'pending' COMMENT '评估状态',
  `evaluated_at` DATETIME DEFAULT NULL COMMENT '回算完成时间',
  `wape` DECIMAL(12,6) DEFAULT NULL COMMENT 'WAPE',
  `mape` DECIMAL(12,6) DEFAULT NULL COMMENT 'MAPE',
  `rmse` DECIMAL(12,6) DEFAULT NULL COMMENT 'RMSE',
  `bias_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '偏差率',
  `stockout_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '缺货率',
  `oversupply_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '过采率',
  `optimization_version` INT NOT NULL DEFAULT 0 COMMENT '优化版本号',
  `optimization_score` DECIMAL(12,6) DEFAULT NULL COMMENT '优化评分',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_forecast_task_no` (`forecast_no`),
  KEY `idx_forecast_task_org` (`org_id`, `horizon_start_date`),
  KEY `idx_forecast_task_status` (`task_status`),
  KEY `idx_forecast_task_evaluation` (`evaluation_status`, `horizon_end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购需求预测任务主表';

-- ---------------------------
-- 3.6.5 采购需求预测任务明细表（scm_purchase_demand_forecast_task_item）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_demand_forecast_task_item`;
CREATE TABLE `scm_purchase_demand_forecast_task_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务明细ID',
  `task_id` BIGINT NOT NULL COMMENT '任务ID',
  `material_id` BIGINT NOT NULL COMMENT '物料ID',
  `material_name` VARCHAR(100) NOT NULL COMMENT '物料名称',
  `material_unit` VARCHAR(20) DEFAULT NULL COMMENT '物料单位',
  `material_category` VARCHAR(50) DEFAULT NULL COMMENT '物料类别',
  `material_segment` VARCHAR(50) DEFAULT NULL COMMENT '物料分层',
  `forecast_demand_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '预测需求量',
  `safety_stock_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '安全库存',
  `avg_daily_demand_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '日均需求量',
  `review_period_days` INT DEFAULT NULL COMMENT '评审周期天数',
  `reorder_point_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '订货点',
  `target_stock_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '目标库存上限',
  `current_stock_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '当前库存',
  `available_stock_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '当前可用库存',
  `inventory_position_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '库存位置量',
  `in_transit_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '在途量',
  `pending_exec_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '待执行量',
  `theoretical_suggested_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '理论建议采购量',
  `suggested_purchase_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '建议采购量',
  `lower_bound_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '置信区间下界',
  `upper_bound_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '置信区间上界',
  `confidence_level` DECIMAL(8,4) NOT NULL DEFAULT 80.0000 COMMENT '置信度',
  `forecast_basis` VARCHAR(500) DEFAULT NULL COMMENT '预测依据说明',
  `priority_level` VARCHAR(20) DEFAULT NULL COMMENT '优先级',
  `model_type` VARCHAR(50) DEFAULT NULL COMMENT '算法类型',
  `feature_snapshot_json` TEXT DEFAULT NULL COMMENT '特征快照JSON',
  `model_param_json` TEXT DEFAULT NULL COMMENT '模型参数JSON',
  `explanation_summary` VARCHAR(500) DEFAULT NULL COMMENT '解释摘要',
  `explanation_detail` VARCHAR(2000) DEFAULT NULL COMMENT '解释详情',
  `explanation_template_code` VARCHAR(50) DEFAULT NULL COMMENT '解释模板编码',
  `explanation_title` VARCHAR(120) DEFAULT NULL COMMENT '解释标题',
  `warning_level` VARCHAR(20) DEFAULT NULL COMMENT '预警级别',
  `warning_message` VARCHAR(500) DEFAULT NULL COMMENT '预警说明',
  `approval_note` VARCHAR(500) DEFAULT NULL COMMENT '审批说明',
  `manual_review_required` TINYINT NOT NULL DEFAULT 0 COMMENT '是否建议人工复核',
  `explanation_factors_json` TEXT DEFAULT NULL COMMENT '解释证据JSON',
  `anomaly_codes` VARCHAR(500) DEFAULT NULL COMMENT '异常编码',
  `explanation_sort_score` DECIMAL(12,6) DEFAULT NULL COMMENT '解释排序分',
  `estimated_unit_price` DECIMAL(10,2) DEFAULT NULL COMMENT '预估单价',
  `anomaly_flags` VARCHAR(1000) DEFAULT NULL COMMENT '异常标签',
  `actual_consumption_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '实际消耗量',
  `abs_error` DECIMAL(18,3) DEFAULT NULL COMMENT '绝对误差',
  `ape` DECIMAL(12,6) DEFAULT NULL COMMENT '绝对百分比误差',
  `rmse` DECIMAL(12,6) DEFAULT NULL COMMENT '均方根误差',
  `bias_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '偏差量',
  `stockout_days` INT DEFAULT NULL COMMENT '缺货天数',
  `oversupply_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '过采量',
  `evaluation_status` VARCHAR(20) DEFAULT 'pending' COMMENT '评估状态',
  `evaluated_at` DATETIME DEFAULT NULL COMMENT '评估完成时间',
  `recipe_drive_ratio` DECIMAL(12,6) DEFAULT NULL COMMENT '菜谱驱动占比',
  `demand_active_ratio` DECIMAL(12,6) DEFAULT NULL COMMENT '需求活跃度',
  `demand_cv` DECIMAL(12,6) DEFAULT NULL COMMENT '需求波动系数',
  `activity_sensitivity` DECIMAL(12,6) DEFAULT NULL COMMENT '活动敏感度',
  `lead_time_days` INT DEFAULT NULL COMMENT '提前期天数',
  `service_level` DECIMAL(12,6) DEFAULT NULL COMMENT '服务水平',
  `effective_lead_time_days` DECIMAL(12,6) DEFAULT NULL COMMENT '有效提前期天数',
  `min_order_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '最小起订量',
  `pack_size` DECIMAL(18,3) DEFAULT NULL COMMENT '包装规格',
  `max_allowed_stock_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '最大允许库存',
  `max_coverage_days` INT DEFAULT NULL COMMENT '最大覆盖天数',
  `recommended_supplier_id` BIGINT DEFAULT NULL COMMENT '推荐供应商ID',
  `recommended_supplier_name` VARCHAR(100) DEFAULT NULL COMMENT '推荐供应商名称',
  `supplier_score` DECIMAL(12,6) DEFAULT NULL COMMENT '供应商综合评分',
  `supplier_fill_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '供应商履约率',
  `supplier_on_time_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '供应商准时率',
  `order_now` TINYINT NOT NULL DEFAULT 0 COMMENT '是否建议立即下单',
  `order_action` VARCHAR(20) DEFAULT NULL COMMENT '下单动作建议',
  `shortage_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '缺货成本',
  `holding_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '库存持有成本',
  `expiry_risk_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '临期报废成本',
  `order_processing_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '下单成本',
  `purchase_price_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '采购价格成本',
  `total_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '综合优化成本',
  `phase_three_risk_flags` VARCHAR(1000) DEFAULT NULL COMMENT '三期风险标记',
  `optimization_version` INT NOT NULL DEFAULT 0 COMMENT '优化版本号',
  `optimization_score` DECIMAL(12,6) DEFAULT NULL COMMENT '优化评分',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_forecast_task_item` (`task_id`, `material_id`),
  KEY `idx_forecast_task_item_material` (`material_id`),
  KEY `idx_forecast_task_item_priority` (`priority_level`),
  KEY `idx_forecast_task_item_segment` (`material_segment`, `model_type`),
  KEY `idx_forecast_task_item_eval` (`evaluation_status`, `evaluated_at`),
  KEY `idx_forecast_task_item_supplier` (`recommended_supplier_id`),
  KEY `idx_forecast_task_item_order_now` (`order_now`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购需求预测任务明细表';

-- ---------------------------
-- 3.6.6 采购需求预测评估表（scm_purchase_demand_forecast_evaluation）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_demand_forecast_evaluation`;
CREATE TABLE `scm_purchase_demand_forecast_evaluation` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评估ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `forecast_id` BIGINT DEFAULT NULL COMMENT '预测单ID',
  `task_id` BIGINT DEFAULT NULL COMMENT '任务ID',
  `task_item_id` BIGINT DEFAULT NULL COMMENT '任务明细ID',
  `forecast_item_id` BIGINT DEFAULT NULL COMMENT '预测明细ID',
  `material_id` BIGINT NOT NULL COMMENT '物料ID',
  `material_name` VARCHAR(100) DEFAULT NULL COMMENT '物料名称',
  `material_segment` VARCHAR(50) DEFAULT NULL COMMENT '物料分层',
  `forecast_date` DATE NOT NULL COMMENT '预测日期',
  `horizon_start_date` DATE NOT NULL COMMENT '预测窗口开始',
  `horizon_end_date` DATE NOT NULL COMMENT '预测窗口结束',
  `predicted_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '预测量',
  `actual_qty` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '实际量',
  `abs_error` DECIMAL(18,3) NOT NULL DEFAULT 0.000 COMMENT '绝对误差',
  `ape` DECIMAL(18,6) NOT NULL DEFAULT 0.000000 COMMENT '绝对百分比误差',
  `rmse` DECIMAL(12,6) DEFAULT NULL COMMENT '均方根误差',
  `bias_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '偏差量',
  `stockout_days` INT DEFAULT NULL COMMENT '缺货天数',
  `oversupply_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '过采量',
  `wape_contribution` DECIMAL(12,6) DEFAULT NULL COMMENT 'WAPE贡献值',
  `model_type` VARCHAR(50) DEFAULT NULL COMMENT '算法类型',
  `actual_source` VARCHAR(50) DEFAULT NULL COMMENT '实际量来源',
  `evaluation_status` VARCHAR(20) DEFAULT 'completed' COMMENT '评估状态',
  `evaluated_at` DATETIME DEFAULT NULL COMMENT '评估完成时间',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_forecast_eval_org_material` (`org_id`, `material_id`, `forecast_date`),
  KEY `idx_forecast_eval_horizon` (`horizon_start_date`, `horizon_end_date`),
  KEY `idx_forecast_eval_task_item` (`task_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购需求预测评估表';

-- ---------------------------
-- 3.6.7 物料预测模型配置表（scm_material_forecast_model_config）
-- ---------------------------
DROP TABLE IF EXISTS `scm_material_forecast_model_config`;
CREATE TABLE `scm_material_forecast_model_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `material_id` BIGINT DEFAULT NULL COMMENT '物料ID',
  `material_category` VARCHAR(50) DEFAULT NULL COMMENT '物料类别',
  `material_segment` VARCHAR(50) NOT NULL COMMENT '物料分层',
  `model_type` VARCHAR(50) NOT NULL COMMENT '模型类型',
  `model_weight` DECIMAL(12,6) DEFAULT NULL COMMENT '模型权重',
  `safety_days` INT DEFAULT NULL COMMENT '安全天数',
  `lead_time_days` INT DEFAULT NULL COMMENT '提前期天数',
  `service_level` DECIMAL(12,6) DEFAULT NULL COMMENT '服务水平',
  `alpha_value` DECIMAL(12,6) DEFAULT NULL COMMENT 'alpha参数',
  `beta_value` DECIMAL(12,6) DEFAULT NULL COMMENT 'beta参数',
  `holiday_factor` DECIMAL(12,6) DEFAULT NULL COMMENT '节假日系数',
  `weekend_factor` DECIMAL(12,6) DEFAULT NULL COMMENT '周末系数',
  `activity_factor` DECIMAL(12,6) DEFAULT NULL COMMENT '活动系数',
  `max_coverage_days` INT DEFAULT NULL COMMENT '最大覆盖天数',
  `recipe_correction_min` DECIMAL(12,6) DEFAULT NULL COMMENT '菜谱修正系数下限',
  `recipe_correction_max` DECIMAL(12,6) DEFAULT NULL COMMENT '菜谱修正系数上限',
  `min_order_qty` DECIMAL(18,3) DEFAULT NULL COMMENT '最小起订量',
  `pack_size` DECIMAL(18,3) DEFAULT NULL COMMENT '包装规格',
  `lead_time_risk_factor` DECIMAL(12,6) DEFAULT NULL COMMENT '提前期波动系数k',
  `shortage_penalty` DECIMAL(12,6) DEFAULT NULL COMMENT '缺货惩罚系数',
  `holding_cost_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '库存持有成本率',
  `waste_cost_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '临期报废成本率',
  `order_cost` DECIMAL(12,2) DEFAULT NULL COMMENT '单次下单成本',
  `optimization_score` DECIMAL(12,6) DEFAULT NULL COMMENT '优化评分',
  `version_no` INT NOT NULL DEFAULT 1 COMMENT '版本号',
  `source_type` VARCHAR(20) NOT NULL DEFAULT 'system' COMMENT '来源：system/manual',
  `effective_start_date` DATE DEFAULT NULL COMMENT '生效开始日期',
  `effective_end_date` DATE DEFAULT NULL COMMENT '生效结束日期',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_model_config_org_segment` (`org_id`, `material_segment`, `status`),
  KEY `idx_model_config_material` (`org_id`, `material_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料预测模型配置表';

-- ---------------------------
-- 3.6.8 供应商履约统计表（scm_supplier_delivery_stat）
-- ---------------------------
DROP TABLE IF EXISTS `scm_supplier_delivery_stat`;
CREATE TABLE `scm_supplier_delivery_stat` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `supplier_id` BIGINT NOT NULL COMMENT '供应商ID',
  `supplier_name` VARCHAR(100) DEFAULT NULL COMMENT '供应商名称',
  `stat_start_date` DATE DEFAULT NULL COMMENT '统计开始日期',
  `stat_end_date` DATE DEFAULT NULL COMMENT '统计结束日期',
  `sample_count` INT NOT NULL DEFAULT 0 COMMENT '样本数',
  `avg_lead_time_days` DECIMAL(12,6) DEFAULT NULL COMMENT '平均提前期',
  `std_lead_time_days` DECIMAL(12,6) DEFAULT NULL COMMENT '提前期标准差',
  `fill_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '履约率',
  `on_time_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '准时率',
  `last_calculated_at` DATETIME DEFAULT NULL COMMENT '最近计算时间',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_supplier_delivery_stat` (`org_id`, `tenant_id`, `supplier_id`),
  KEY `idx_supplier_delivery_org` (`org_id`, `stat_end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商履约统计表';

-- ---------------------------
-- 3.6.9 采购需求预测自动优化日志表（scm_purchase_demand_forecast_optimization_log）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_demand_forecast_optimization_log`;
CREATE TABLE `scm_purchase_demand_forecast_optimization_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `material_id` BIGINT DEFAULT NULL COMMENT '物料ID',
  `material_category` VARCHAR(50) DEFAULT NULL COMMENT '物料类别',
  `material_segment` VARCHAR(50) NOT NULL COMMENT '物料分层',
  `model_type` VARCHAR(50) NOT NULL COMMENT '模型类型',
  `candidate_config_json` TEXT DEFAULT NULL COMMENT '候选参数集',
  `selected_config_json` TEXT DEFAULT NULL COMMENT '选中参数集',
  `score` DECIMAL(12,6) DEFAULT NULL COMMENT '目标函数评分',
  `wape` DECIMAL(12,6) DEFAULT NULL COMMENT 'WAPE',
  `stockout_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '缺货率',
  `oversupply_rate` DECIMAL(12,6) DEFAULT NULL COMMENT '过采率',
  `sample_forecast_count` INT NOT NULL DEFAULT 0 COMMENT '参与优化的预测样本数',
  `version_no` INT NOT NULL DEFAULT 1 COMMENT '版本号',
  `trigger_type` VARCHAR(20) NOT NULL DEFAULT 'auto' COMMENT '触发方式',
  `effective_date` DATE DEFAULT NULL COMMENT '生效日期',
  `optimized_at` DATETIME DEFAULT NULL COMMENT '优化完成时间',
  `rollback_applied` TINYINT NOT NULL DEFAULT 0 COMMENT '是否触发回退',
  `previous_version_no` INT DEFAULT NULL COMMENT '回退前版本号',
  `previous_score` DECIMAL(12,6) DEFAULT NULL COMMENT '回退前评分',
  `rollback_reason` VARCHAR(255) DEFAULT NULL COMMENT '回退原因',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_opt_log_org_segment` (`org_id`, `material_segment`, `optimized_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购需求预测自动优化日志表';

-- ---------------------------
-- 3.7 采购订单表（scm_purchase_order）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_order`;
CREATE TABLE `scm_purchase_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `plan_id` BIGINT DEFAULT NULL COMMENT '主关联计划ID（兼容字段，多计划关联以明细 plan_item_id 为准）',
  `supplier_id` BIGINT NOT NULL COMMENT '供应商ID',
  `supplier_name` VARCHAR(100) NOT NULL COMMENT '供应商名称（冗余）',
  `order_date` DATE NOT NULL COMMENT '订单日期',
  `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '订单总金额',
  `expected_delivery_at` DATETIME DEFAULT NULL COMMENT '预计交货时间',
  `actual_delivery_at` DATETIME DEFAULT NULL COMMENT '实际交货时间',
  `delivery_address` VARCHAR(200) DEFAULT NULL COMMENT '收货地址',
  `logistics_no` VARCHAR(100) DEFAULT NULL COMMENT '物流单号',
  `logistics_company` VARCHAR(100) DEFAULT NULL COMMENT '物流公司',
  `logistics_status` VARCHAR(30) DEFAULT NULL COMMENT '物流状态：pending=待发货，shipped=已发货，in_transit=运输中，arrived=已到货',
  `logistics_remark` VARCHAR(500) DEFAULT NULL COMMENT '物流备注',
  `logistics_source_type` VARCHAR(30) DEFAULT NULL COMMENT '物流来源：manual=手工录入，third_party=第三方接口',
  `logistics_sync_payload` TEXT DEFAULT NULL COMMENT '物流第三方同步原始数据',
  `shipped_at` DATETIME DEFAULT NULL COMMENT '发货时间',
  `arrived_at` DATETIME DEFAULT NULL COMMENT '到货时间',
  `logistics_attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '物流附件名称',
  `logistics_attachment_url` VARCHAR(1000) DEFAULT NULL COMMENT '物流附件地址',
  `inspection_report_no` VARCHAR(100) DEFAULT NULL COMMENT '检测报告编号',
  `inspection_result` VARCHAR(100) DEFAULT NULL COMMENT '检测结果',
  `inspection_agency` VARCHAR(100) DEFAULT NULL COMMENT '检测机构',
  `inspection_at` DATETIME DEFAULT NULL COMMENT '检测时间',
  `inspection_remark` VARCHAR(500) DEFAULT NULL COMMENT '检测备注',
  `inspection_source_type` VARCHAR(30) DEFAULT NULL COMMENT '检测来源：manual=手工录入，third_party=第三方接口',
  `inspection_sync_payload` TEXT DEFAULT NULL COMMENT '检测第三方同步原始数据',
  `inspection_attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '检测附件名称',
  `inspection_attachment_url` VARCHAR(1000) DEFAULT NULL COMMENT '检测附件地址',
  `attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '附件名称',
  `attachment_url` VARCHAR(1000) DEFAULT NULL COMMENT '附件地址',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `status` VARCHAR(30) NOT NULL DEFAULT 'pending_submit' COMMENT '状态：pending_submit=草稿，pending_approve=待审核，approved=已审核，rejected=已驳回，pending_void_approve=待作废审核，voided=已作废，delivering=运输中，pending_receipt=待入库，received=已收货，inspected=已验收，completed=已完成，closed=已关闭，cancelled=已取消',
  `approved_by` BIGINT DEFAULT NULL COMMENT '审核人ID',
  `approved_at` DATETIME DEFAULT NULL COMMENT '审核时间',
  `approve_remark` VARCHAR(500) DEFAULT NULL COMMENT '审批备注',
  `void_reason` VARCHAR(500) DEFAULT NULL COMMENT '作废原因',
  `void_requested_by` BIGINT DEFAULT NULL COMMENT '作废申请人ID',
  `void_requested_at` DATETIME DEFAULT NULL COMMENT '作废申请时间',
  `void_audit_by` BIGINT DEFAULT NULL COMMENT '作废审核人ID',
  `void_audit_at` DATETIME DEFAULT NULL COMMENT '作废审核时间',
  `void_audit_remark` VARCHAR(500) DEFAULT NULL COMMENT '作废审核备注',
  `trace_batch_id` VARCHAR(100) DEFAULT NULL COMMENT '溯源批次码',
  `trace_origin` VARCHAR(200) DEFAULT NULL COMMENT '溯源产地/来源',
  `trace_remark` VARCHAR(500) DEFAULT NULL COMMENT '溯源备注',
  `trace_source_type` VARCHAR(30) DEFAULT NULL COMMENT '溯源来源：manual=手工录入，third_party=第三方接口',
  `trace_sync_payload` TEXT DEFAULT NULL COMMENT '溯源第三方同步原始数据',
  `trace_attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '溯源附件名称',
  `trace_attachment_url` VARCHAR(1000) DEFAULT NULL COMMENT '溯源附件地址',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_order_status` (`status`),
  KEY `idx_order_supplier` (`supplier_id`),
  KEY `idx_order_plan` (`plan_id`),
  KEY `idx_order_org` (`org_id`),
  KEY `idx_order_date` (`order_date`),
  KEY `idx_order_tenant` (`tenant_id`),
  KEY `idx_order_created_at` (`created_at`),
  KEY `idx_order_delivery` (`expected_delivery_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购订单表';

-- ---------------------------
-- 3.8 采购订单附件表（scm_purchase_order_attachment）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_order_attachment`;
CREATE TABLE `scm_purchase_order_attachment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `order_id` BIGINT NOT NULL COMMENT '采购订单ID',
  `attachment_type` VARCHAR(30) NOT NULL COMMENT '附件类型：logistics=物流，inspection=检测，traceability=溯源',
  `file_name` VARCHAR(255) NOT NULL COMMENT '附件名称',
  `file_size` VARCHAR(30) DEFAULT NULL COMMENT '附件大小',
  `file_url` VARCHAR(1000) NOT NULL COMMENT '附件地址',
  `sort_order` INT NOT NULL DEFAULT 1 COMMENT '排序',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_order_attachment_order` (`order_id`),
  KEY `idx_order_attachment_type` (`attachment_type`),
  KEY `idx_order_attachment_org` (`org_id`),
  KEY `idx_order_attachment_tenant` (`tenant_id`),
  KEY `idx_order_attachment_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购订单维护附件表';

-- ---------------------------
-- 3.7 采购订单明细表（scm_purchase_order_item）
-- ---------------------------
DROP TABLE IF EXISTS `scm_purchase_order_item`;
CREATE TABLE `scm_purchase_order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '明细ID',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `plan_item_id` BIGINT DEFAULT NULL COMMENT '关联采购计划明细ID',
  `material_id` BIGINT NOT NULL COMMENT '物料ID',
  `material_name` VARCHAR(100) NOT NULL COMMENT '物料名称（冗余）',
  `material_spec` VARCHAR(100) DEFAULT NULL COMMENT '规格（冗余）',
  `material_unit` VARCHAR(20) NOT NULL COMMENT '单位（冗余）',
  `order_qty` DECIMAL(10,3) NOT NULL COMMENT '订购数量',
  `received_qty` DECIMAL(10,3) DEFAULT 0.000 COMMENT '已收货数量',
  `inbound_qty` DECIMAL(10,3) DEFAULT 0.000 COMMENT '已入库数量',
  `remaining_inbound_qty` DECIMAL(10,3) DEFAULT 0.000 COMMENT '剩余待入库数量',
  `unit_price` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `total_amount` DECIMAL(12,2) NOT NULL COMMENT '小计金额',
  `remark` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_order_item_order` (`order_id`),
  KEY `idx_order_item_material` (`material_id`),
  KEY `idx_order_item_plan_item` (`plan_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购订单明细表';

-- ---------------------------
-- 3.8 收货验收记录表（scm_receipt_record）
-- ---------------------------
DROP TABLE IF EXISTS `scm_receipt_record`;
CREATE TABLE `scm_receipt_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '验收记录ID',
  `receipt_no` VARCHAR(50) NOT NULL COMMENT '验收单编号',
  `order_id` BIGINT NOT NULL COMMENT '采购订单ID',
  `order_no` VARCHAR(50) NOT NULL COMMENT '采购订单编号（冗余）',
  `supplier_id` BIGINT NOT NULL COMMENT '供应商ID',
  `inspector_id` BIGINT NOT NULL COMMENT '验收人ID',
  `inspected_at` DATETIME NOT NULL COMMENT '验收时间',
  `result` VARCHAR(20) NOT NULL COMMENT '验收结果：pass=合格，partial=部分合格，reject=不合格',
  `reject_reason` VARCHAR(500) DEFAULT NULL COMMENT '不合格原因',
  `photos` JSON DEFAULT NULL COMMENT '验收照片（JSON数组）',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `trace_batch_id` VARCHAR(100) DEFAULT NULL COMMENT '溯源批次码',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_receipt_no` (`receipt_no`),
  KEY `idx_receipt_order` (`order_id`),
  KEY `idx_receipt_supplier` (`supplier_id`),
  KEY `idx_receipt_org` (`org_id`),
  KEY `idx_receipt_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收货验收记录表';
