-- ============================================================
-- 智慧厨房管理平台 - 数据库初始化脚本（第七部分）
-- 系统基础模块（sys_）
-- ============================================================

USE `smart_food_safety`;

-- ---------------------------
-- 9.1 员工档案表（sys_employee）
-- ---------------------------
DROP TABLE IF EXISTS `sys_employee`;
CREATE TABLE `sys_employee` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '员工ID',
  `employee_no` VARCHAR(50) NOT NULL COMMENT '员工工号',
  `user_id` BIGINT DEFAULT NULL COMMENT '关联系统用户ID',
  `real_name` VARCHAR(50) NOT NULL COMMENT '真实姓名',
  `gender` TINYINT DEFAULT 0 COMMENT '性别：0=未知，1=男，2=女',
  `id_card` VARCHAR(255) DEFAULT NULL COMMENT '身份证号（加密存储）',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `avatar_url` VARCHAR(500) DEFAULT NULL COMMENT '照片URL',
  `department` VARCHAR(100) DEFAULT NULL COMMENT '所属部门',
  `position` VARCHAR(100) DEFAULT NULL COMMENT '岗位',
  `hire_date` DATE DEFAULT NULL COMMENT '入职日期',
  `leave_date` DATE DEFAULT NULL COMMENT '离职日期',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active=在职，left=离职',
  `health_cert_status` VARCHAR(20) DEFAULT 'pending' COMMENT '健康证状态（冗余）',
  `face_enrolled` TINYINT DEFAULT 0 COMMENT '人脸是否已录入：0=未录入，1=已录入',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_employee_no` (`employee_no`, `org_id`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_emp_user` (`user_id`),
  KEY `idx_emp_status` (`status`),
  KEY `idx_emp_org` (`org_id`),
  KEY `idx_emp_cert_status` (`health_cert_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工档案表';

-- ---------------------------
-- 9.2 操作审计日志表（sys_audit_log）
-- ---------------------------
DROP TABLE IF EXISTS `sys_audit_log`;
CREATE TABLE `sys_audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `user_id` BIGINT NOT NULL COMMENT '操作人ID',
  `user_name` VARCHAR(50) NOT NULL COMMENT '操作人用户名（冗余）',
  `real_name` VARCHAR(50) DEFAULT NULL COMMENT '操作人真实姓名（冗余）',
  `operation_type` VARCHAR(30) NOT NULL COMMENT '操作类型：create=新增，update=修改，delete=删除，approve=审批，login=登录，export=导出，import=导入',
  `module_code` VARCHAR(50) NOT NULL COMMENT '模块编码（如scm_supplier）',
  `module_name` VARCHAR(50) NOT NULL COMMENT '模块名称（如供应商管理）',
  `target_id` BIGINT DEFAULT NULL COMMENT '操作对象ID',
  `target_no` VARCHAR(100) DEFAULT NULL COMMENT '操作对象编号',
  `operation_desc` VARCHAR(500) NOT NULL COMMENT '操作描述',
  `before_data` JSON DEFAULT NULL COMMENT '操作前数据快照（JSON格式）',
  `after_data` JSON DEFAULT NULL COMMENT '操作后数据快照（JSON格式）',
  `ip_address` VARCHAR(50) DEFAULT NULL COMMENT '操作IP地址',
  `user_agent` VARCHAR(500) DEFAULT NULL COMMENT '用户代理',
  `source_terminal` VARCHAR(20) DEFAULT NULL COMMENT '来源终端: Web/PC/Mobile/Pad/KDS/Device/API/OfflineSync',
  `device_id` BIGINT DEFAULT NULL COMMENT '关联设备ID（监控审计）',
  `recording_id` BIGINT DEFAULT NULL COMMENT '关联录像ID（监控审计）',
  `result` VARCHAR(20) NOT NULL DEFAULT 'success' COMMENT '操作结果：success=成功，fail=失败，exception=异常',
  `error_msg` VARCHAR(500) DEFAULT NULL COMMENT '错误信息（操作失败时）',
  `org_id` BIGINT DEFAULT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  PRIMARY KEY (`id`),
  KEY `idx_al_user` (`user_id`),
  KEY `idx_al_type` (`operation_type`),
  KEY `idx_al_module` (`module_code`),
  KEY `idx_al_target` (`target_id`),
  KEY `idx_al_org` (`org_id`),
  KEY `idx_al_created_at` (`created_at`),
  KEY `idx_al_device` (`device_id`),
  KEY `idx_al_recording` (`recording_id`),
  KEY `idx_al_terminal` (`source_terminal`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作审计日志表';

-- ---------------------------
-- 9.3 用餐评价表（sys_meal_review）
-- ---------------------------
DROP TABLE IF EXISTS `sys_meal_review`;
CREATE TABLE `sys_meal_review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '评价ID',
  `review_no` VARCHAR(50) NOT NULL COMMENT '评价编号',
  `source` VARCHAR(20) NOT NULL DEFAULT 'meal' COMMENT '来源：meal=用餐评价，supervision=监管反馈，manual=人工录入',
  `employee_id` BIGINT NOT NULL COMMENT '评价人ID',
  `employee_name` VARCHAR(50) DEFAULT NULL COMMENT '评价人姓名（冗余）',
  `plan_id` BIGINT DEFAULT NULL COMMENT '关联菜谱计划ID',
  `menu_id` BIGINT DEFAULT NULL COMMENT '评价菜品ID',
  `menu_name` VARCHAR(100) DEFAULT NULL COMMENT '菜品名称（冗余）',
  `review_date` DATE NOT NULL COMMENT '评价日期',
  `meal_type` VARCHAR(20) DEFAULT NULL COMMENT '餐次：breakfast/lunch/dinner',
  `overall_score` INT NOT NULL COMMENT '综合评分（1-5）',
  `taste_score` INT DEFAULT NULL COMMENT '口味评分（1-5）',
  `nutrition_score` INT DEFAULT NULL COMMENT '营养评分（1-5）',
  `portion_score` INT DEFAULT NULL COMMENT '份量评分（1-5）',
  `content` VARCHAR(1000) DEFAULT NULL COMMENT '评价内容',
  `images` JSON DEFAULT NULL COMMENT '评价图片（JSON数组）',
  `tags` JSON DEFAULT NULL COMMENT '评价标签（JSON数组）',
  `points` INT DEFAULT 0 COMMENT '获得积分',
  `reply_content` VARCHAR(1000) DEFAULT NULL COMMENT '回复内容',
  `reply_by` BIGINT DEFAULT NULL COMMENT '回复人ID',
  `reply_by_name` VARCHAR(50) DEFAULT NULL COMMENT '回复人姓名',
  `reply_at` DATETIME DEFAULT NULL COMMENT '回复时间',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_no` (`review_no`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_mr_employee` (`employee_id`),
  KEY `idx_mr_date` (`review_date`),
  KEY `idx_mr_overall_score` (`overall_score`),
  KEY `idx_mr_source` (`source`),
  KEY `idx_mr_org` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用餐评价表';

-- ---------------------------
-- 9.4 投诉表（sys_complaint）
-- ---------------------------
DROP TABLE IF EXISTS `sys_complaint`;
CREATE TABLE `sys_complaint` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '投诉ID',
  `complaint_no` VARCHAR(50) NOT NULL COMMENT '投诉编号',
  `complaint_type` VARCHAR(50) DEFAULT NULL COMMENT '投诉类型：food=食品问题，service=服务问题，hygiene=卫生问题，other=其他',
  `source` VARCHAR(20) NOT NULL COMMENT '来源：meal=用餐评价，supervision=监管反馈，manual=人工录入',
  `title` VARCHAR(200) NOT NULL COMMENT '投诉标题',
  `description` VARCHAR(1000) DEFAULT NULL COMMENT '投诉描述',
  `submitter_id` BIGINT NOT NULL COMMENT '投诉人ID',
  `submitter_name` VARCHAR(50) NOT NULL COMMENT '投诉人姓名',
  `submitter_phone` VARCHAR(20) DEFAULT NULL COMMENT '投诉人电话',
  `related_menu_id` BIGINT DEFAULT NULL COMMENT '关联菜品ID',
  `related_menu_name` VARCHAR(100) DEFAULT NULL COMMENT '关联菜品名称',
  `images` JSON DEFAULT NULL COMMENT '投诉图片（JSON数组）',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '状态：pending=待处理，dispatched=已派单，processing=处理中，closed=已闭环',
  `priority` VARCHAR(20) DEFAULT 'medium' COMMENT '优先级：high=高，medium=中，low=低',
  `satisfaction` VARCHAR(20) DEFAULT NULL COMMENT '满意度：satisfied=满意，neutral=一般，dissatisfied=不满意',
  `satisfaction_remark` VARCHAR(200) DEFAULT NULL COMMENT '满意度备注',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_complaint_no` (`complaint_no`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_complaint_submitter` (`submitter_id`),
  KEY `idx_complaint_status` (`status`),
  KEY `idx_complaint_type` (`complaint_type`),
  KEY `idx_complaint_source` (`source`),
  KEY `idx_complaint_org` (`org_id`),
  KEY `idx_complaint_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投诉表';

-- ---------------------------
-- 9.5 投诉派单表（sys_complaint_dispatch）
-- ---------------------------
DROP TABLE IF EXISTS `sys_complaint_dispatch`;
CREATE TABLE `sys_complaint_dispatch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '派单ID',
  `dispatch_no` VARCHAR(50) NOT NULL COMMENT '派单编号',
  `complaint_id` BIGINT NOT NULL COMMENT '关联投诉ID',
  `complaint_no` VARCHAR(50) NOT NULL COMMENT '投诉编号（冗余）',
  `complaint_title` VARCHAR(200) DEFAULT NULL COMMENT '投诉标题（冗余）',
  `dispatch_type` VARCHAR(20) NOT NULL COMMENT '派单方式：auto=自动派单，manual=人工派单',
  `assigner_id` BIGINT DEFAULT NULL COMMENT '派单人ID（人工派单时）',
  `assigner_name` VARCHAR(50) DEFAULT NULL COMMENT '派单人姓名',
  `handler_id` BIGINT NOT NULL COMMENT '处理人ID',
  `handler_name` VARCHAR(50) NOT NULL COMMENT '处理人姓名',
  `deadline` DATETIME DEFAULT NULL COMMENT '截止时间',
  `priority` VARCHAR(20) DEFAULT NULL COMMENT '优先级：high/medium/low',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '派单备注',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '状态：pending=待处理，processing=处理中，completed=已完成，cancelled=已取消',
  `handle_result` VARCHAR(500) DEFAULT NULL COMMENT '处理结果',
  `handle_images` JSON DEFAULT NULL COMMENT '处理图片（JSON数组）',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dispatch_no` (`dispatch_no`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_dispatch_complaint` (`complaint_id`),
  KEY `idx_dispatch_handler` (`handler_id`),
  KEY `idx_dispatch_assigner` (`assigner_id`),
  KEY `idx_dispatch_status` (`status`),
  KEY `idx_dispatch_type` (`dispatch_type`),
  KEY `idx_dispatch_org` (`org_id`),
  KEY `idx_dispatch_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投诉派单表';

-- ---------------------------
-- 9.6 投诉工单处理记录表（sys_work_order_record）
-- ---------------------------
DROP TABLE IF EXISTS `sys_work_order_record`;
CREATE TABLE `sys_work_order_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `dispatch_id` BIGINT NOT NULL COMMENT '关联派单ID',
  `complaint_id` BIGINT NOT NULL COMMENT '关联投诉ID',
  `action` VARCHAR(50) NOT NULL COMMENT '操作类型：dispatch=派单，reassign=改派，process=处理，complete=完成，cancel=取消',
  `action_name` VARCHAR(50) NOT NULL COMMENT '操作名称',
  `operator_id` BIGINT NOT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(50) NOT NULL COMMENT '操作人姓名',
  `content` VARCHAR(500) DEFAULT NULL COMMENT '操作内容',
  `images` JSON DEFAULT NULL COMMENT '处理图片（JSON数组）',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_wor_dispatch` (`dispatch_id`),
  KEY `idx_wor_complaint` (`complaint_id`),
  KEY `idx_wor_operator` (`operator_id`),
  KEY `idx_wor_action` (`action`),
  KEY `idx_wor_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投诉工单处理记录表';

-- ---------------------------
-- 9.7 系统字典表（sys_dict）
-- ---------------------------
DROP TABLE IF EXISTS `sys_dict`;
CREATE TABLE `sys_dict` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '字典ID',
  `dict_type` VARCHAR(50) NOT NULL COMMENT '字典类型（如：material_category、device_type）',
  `dict_code` VARCHAR(100) NOT NULL COMMENT '字典编码（唯一值）',
  `dict_name` VARCHAR(100) NOT NULL COMMENT '字典显示名称',
  `dict_value` VARCHAR(200) DEFAULT NULL COMMENT '字典附加值',
  `parent_code` VARCHAR(100) DEFAULT NULL COMMENT '父级编码',
  `sort_order` INT DEFAULT 0 COMMENT '排序',
  `is_system` TINYINT DEFAULT 0 COMMENT '是否系统内置：0=否，1=是（不可删除）',
  `remark` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active=启用，inactive=停用',
  `area_coefficient` DECIMAL(18,4) DEFAULT NULL COMMENT '物料类别统一面积系数（㎡/单件），仅material_category使用',
  `area_coefficient_source` VARCHAR(20) DEFAULT NULL COMMENT '面积系数来源：system/manual/ai',
  `ai_suggested_area_coefficient` DECIMAL(18,4) DEFAULT NULL COMMENT '最近一次AI建议面积系数',
  `ai_suggestion_reason` VARCHAR(300) DEFAULT NULL COMMENT 'AI建议依据摘要',
  `ai_suggestion_generated_at` DATETIME DEFAULT NULL COMMENT 'AI建议生成时间',
  `org_id` BIGINT DEFAULT 0 COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_tenant_type_code` (`tenant_id`, `dict_type`, `dict_code`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_dict_type` (`dict_type`),
  KEY `idx_dict_parent` (`parent_code`),
  KEY `idx_dict_tenant_type_status` (`tenant_id`, `dict_type`, `status`),
  KEY `idx_dict_tenant_type_name` (`tenant_id`, `dict_type`, `dict_name`),
  KEY `idx_dict_org` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统字典表';

INSERT INTO `sys_dict` (
  `id`, `dict_type`, `dict_code`, `dict_name`, `dict_value`, `sort_order`, `is_system`,
  `remark`, `status`, `area_coefficient`, `area_coefficient_source`,
  `ai_suggested_area_coefficient`, `ai_suggestion_reason`, `ai_suggestion_generated_at`,
  `org_id`, `tenant_id`, `created_by`, `updated_by`
) VALUES
(1, 'warehouse_type', 'normal', '常温库', 'normal', 10, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(2, 'warehouse_type', 'cold', '冷藏库', 'cold', 20, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(3, 'warehouse_type', 'freeze', '冷冻库', 'freeze', 30, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(4, 'warehouse_type', 'dry', '干货库', 'dry', 40, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(5, 'material_category', 'VEGETABLE', '蔬菜', '蔬菜', 10, 1, '系统内置', 'active', 0.2500, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(6, 'material_category', 'MEAT', '肉类', '肉类', 20, 1, '系统内置', 'active', 0.1800, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(7, 'material_category', 'SEAFOOD', '水产', '水产', 30, 1, '系统内置', 'active', 0.2200, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(8, 'material_category', 'SEASONING', '调料', '调料', 40, 1, '系统内置', 'active', 0.0500, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(9, 'material_category', 'GRAIN_OIL', '粮油', '粮油', 50, 1, '系统内置', 'active', 0.1200, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(10, 'material_category', 'DAIRY', '乳制品', '乳制品', 60, 1, '系统内置', 'active', 0.1600, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(11, 'material_category', 'FRUIT', '水果', '水果', 70, 1, '系统内置', 'active', 0.2800, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(12, 'material_category', 'OCEAN_FOOD', '海鲜', '海鲜', 80, 1, '系统内置', 'active', 0.2400, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(13, 'material_category', 'EGG', '蛋类', '蛋类', 90, 1, '系统内置', 'active', 0.1500, 'system', NULL, NULL, NULL, 1, 1, 1, 1),
(14, 'supplier_type', 'VEGETABLE', '蔬菜', '蔬菜', 10, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(15, 'supplier_type', 'MEAT', '肉类', '肉类', 20, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(16, 'supplier_type', 'SEAFOOD', '水产', '水产', 30, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(17, 'supplier_type', 'SEASONING', '调料', '调料', 40, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(18, 'supplier_type', 'GRAIN_OIL', '粮油', '粮油', 50, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(19, 'supplier_type', 'DAIRY', '乳制品', '乳制品', 60, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(20, 'supplier_type', 'DRINK', '饮料', '饮料', 70, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(21, 'supplier_type', 'FROZEN_FOOD', '冷冻食品', '冷冻食品', 80, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(22, 'device_type', 'camera', '监控摄像头', 'camera', 10, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(23, 'device_type', 'sensor', '温湿度传感器', 'sensor', 20, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(24, 'device_type', 'scale', '食材检测设备', 'scale', 30, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(25, 'device_type', 'gas_detector', '气体监测设备', 'gas_detector', 40, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(26, 'device_type', 'sample_terminal', '智能留样设备', 'sample_terminal', 50, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(27, 'device_type', 'health_terminal', '智能晨检设备', 'health_terminal', 60, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(28, 'device_type', 'temperature_humidity', '温湿度探头', 'temperature_humidity', 70, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(29, 'org_type', 'group', '集团', 'group', 10, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(30, 'org_type', 'company', '分公司', 'company', 20, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(31, 'org_type', 'canteen', '食堂', 'canteen', 30, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(32, 'org_type', 'dept', '部门', 'dept', 40, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(33, 'employee_position', 'chef', '厨师', 'chef', 10, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(34, 'employee_position', 'cookworker', '厨工', 'cookworker', 20, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(35, 'employee_position', 'manager', '店长', 'manager', 30, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1),
(36, 'employee_position', 'purchaser', '采购员', 'purchaser', 40, 1, '系统内置', 'active', NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1);

-- ---------------------------
-- 9.8 物料类别面积系数修正版本表（sys_dict_area_coefficient_correction）
-- ---------------------------
DROP TABLE IF EXISTS `sys_dict_area_coefficient_correction`;
CREATE TABLE `sys_dict_area_coefficient_correction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '修正记录ID',
  `dict_id` BIGINT NOT NULL COMMENT '字典项ID',
  `dict_type` VARCHAR(50) NOT NULL COMMENT '字典类型',
  `dict_code` VARCHAR(100) NOT NULL COMMENT '字典编码',
  `dict_name` VARCHAR(100) NOT NULL COMMENT '字典名称',
  `dict_value` VARCHAR(200) DEFAULT NULL COMMENT '字典值',
  `correction_version` INT NOT NULL COMMENT '修正版本号',
  `old_area_coefficient` DECIMAL(18,4) NOT NULL COMMENT '旧面积系数',
  `new_area_coefficient` DECIMAL(18,4) NOT NULL COMMENT '新面积系数',
  `old_area_coefficient_source` VARCHAR(20) DEFAULT NULL COMMENT '旧面积系数来源',
  `new_area_coefficient_source` VARCHAR(20) DEFAULT NULL COMMENT '新面积系数来源',
  `impact_scope` VARCHAR(30) NOT NULL DEFAULT 'subsequent_only' COMMENT '影响口径：subsequent_only=仅后续生效，manual_recalc=管理员可手动回溯重算',
  `impact_acknowledged` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已确认影响提示：0=否，1=是',
  `impact_acknowledged_at` DATETIME DEFAULT NULL COMMENT '确认影响提示时间',
  `recalc_status` VARCHAR(30) NOT NULL DEFAULT 'not_applicable' COMMENT '重算状态：not_applicable/pending/running/completed/failed',
  `recalc_task_id` BIGINT DEFAULT NULL COMMENT '最近一次重算任务ID',
  `recalc_completed_at` DATETIME DEFAULT NULL COMMENT '重算完成时间',
  `operator_id` BIGINT DEFAULT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(100) DEFAULT NULL COMMENT '操作人名称',
  `org_id` BIGINT NOT NULL DEFAULT 0 COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_area_correction_version` (`tenant_id`, `dict_id`, `correction_version`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_dict_area_correction_dict` (`dict_id`),
  KEY `idx_dict_area_correction_status` (`recalc_status`),
  KEY `idx_dict_area_correction_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料类别面积系数修正版本表';

-- ---------------------------
-- 9.9 物料类别面积系数当前冻结锁表（sys_dict_area_coefficient_lock）
-- ---------------------------
DROP TABLE IF EXISTS `sys_dict_area_coefficient_lock`;
CREATE TABLE `sys_dict_area_coefficient_lock` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '锁记录ID',
  `dict_id` BIGINT NOT NULL COMMENT '字典项ID',
  `dict_type` VARCHAR(50) NOT NULL COMMENT '字典类型',
  `dict_code` VARCHAR(100) NOT NULL COMMENT '字典编码',
  `dict_name` VARCHAR(100) NOT NULL COMMENT '字典名称',
  `dict_value` VARCHAR(200) DEFAULT NULL COMMENT '字典值',
  `lock_status` VARCHAR(20) NOT NULL DEFAULT 'unlocked' COMMENT '锁状态：unlocked=未锁定，locked=已锁定',
  `lock_type` VARCHAR(30) DEFAULT NULL COMMENT '锁类型：coefficient_update=系数修正，history_recalc=历史重算',
  `lock_reason` VARCHAR(500) DEFAULT NULL COMMENT '锁定原因',
  `correction_id` BIGINT DEFAULT NULL COMMENT '关联修正记录ID',
  `correction_version` INT DEFAULT NULL COMMENT '关联修正版本号',
  `task_id` BIGINT DEFAULT NULL COMMENT '关联重算任务ID',
  `locked_by` BIGINT DEFAULT NULL COMMENT '锁定操作人ID',
  `locked_by_name` VARCHAR(100) DEFAULT NULL COMMENT '锁定操作人名称',
  `locked_at` DATETIME DEFAULT NULL COMMENT '锁定时间',
  `released_by` BIGINT DEFAULT NULL COMMENT '解锁操作人ID',
  `released_by_name` VARCHAR(100) DEFAULT NULL COMMENT '解锁操作人名称',
  `released_at` DATETIME DEFAULT NULL COMMENT '解锁时间',
  `org_id` BIGINT NOT NULL DEFAULT 0 COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_area_lock_dict` (`tenant_id`, `dict_id`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_dict_area_lock_status` (`lock_status`),
  KEY `idx_dict_area_lock_task` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料类别面积系数当前冻结锁表';

-- ---------------------------
-- 9.10 物料类别面积系数历史重算任务表（sys_dict_area_coefficient_recalc_task）
-- ---------------------------
DROP TABLE IF EXISTS `sys_dict_area_coefficient_recalc_task`;
CREATE TABLE `sys_dict_area_coefficient_recalc_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `task_no` VARCHAR(50) NOT NULL COMMENT '任务编号',
  `dict_id` BIGINT NOT NULL COMMENT '字典项ID',
  `dict_type` VARCHAR(50) NOT NULL COMMENT '字典类型',
  `dict_code` VARCHAR(100) NOT NULL COMMENT '字典编码',
  `dict_name` VARCHAR(100) NOT NULL COMMENT '字典名称',
  `dict_value` VARCHAR(200) DEFAULT NULL COMMENT '字典值',
  `correction_id` BIGINT NOT NULL COMMENT '关联修正记录ID',
  `correction_version` INT NOT NULL COMMENT '关联修正版本号',
  `old_area_coefficient` DECIMAL(18,4) NOT NULL COMMENT '旧面积系数',
  `new_area_coefficient` DECIMAL(18,4) NOT NULL COMMENT '新面积系数',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '任务状态：pending/running/completed/failed',
  `progress_percent` INT NOT NULL DEFAULT 0 COMMENT '任务进度百分比',
  `total_steps` INT NOT NULL DEFAULT 0 COMMENT '总步骤数',
  `completed_steps` INT NOT NULL DEFAULT 0 COMMENT '已完成步骤数',
  `success_count` INT NOT NULL DEFAULT 0 COMMENT '成功步骤数',
  `failure_count` INT NOT NULL DEFAULT 0 COMMENT '失败步骤数',
  `result_message` VARCHAR(1000) DEFAULT NULL COMMENT '任务结果消息',
  `started_by` BIGINT DEFAULT NULL COMMENT '发起人ID',
  `started_by_name` VARCHAR(100) DEFAULT NULL COMMENT '发起人名称',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `finished_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `org_id` BIGINT NOT NULL DEFAULT 0 COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_area_recalc_task_no` (`task_no`),
  KEY `idx_dict_area_recalc_task_dict` (`dict_id`),
  KEY `idx_dict_area_recalc_task_status` (`status`),
  KEY `idx_dict_area_recalc_task_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料类别面积系数历史重算任务表';

-- ---------------------------
-- 9.11 物料类别面积系数历史重算明细表（sys_dict_area_coefficient_recalc_detail）
-- ---------------------------
DROP TABLE IF EXISTS `sys_dict_area_coefficient_recalc_detail`;
CREATE TABLE `sys_dict_area_coefficient_recalc_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '明细ID',
  `task_id` BIGINT NOT NULL COMMENT '任务ID',
  `detail_code` VARCHAR(50) NOT NULL COMMENT '明细编码',
  `detail_name` VARCHAR(100) NOT NULL COMMENT '明细名称',
  `detail_type` VARCHAR(30) NOT NULL COMMENT '明细类型：inventory/report/procurement/ai_measurement/summary',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '执行状态：pending/running/completed/failed',
  `affected_record_count` BIGINT NOT NULL DEFAULT 0 COMMENT '影响记录数',
  `quantity_total` DECIMAL(18,4) DEFAULT 0.0000 COMMENT '总业务数量',
  `old_area_total` DECIMAL(18,4) DEFAULT 0.0000 COMMENT '旧系数对应总面积',
  `new_area_total` DECIMAL(18,4) DEFAULT 0.0000 COMMENT '新系数对应总面积',
  `delta_area_total` DECIMAL(18,4) DEFAULT 0.0000 COMMENT '面积差值',
  `detail_message` VARCHAR(1000) DEFAULT NULL COMMENT '明细结果消息',
  `snapshot_payload` JSON DEFAULT NULL COMMENT '重算快照明细',
  `org_id` BIGINT NOT NULL DEFAULT 0 COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_dict_area_recalc_detail_task` (`task_id`),
  KEY `idx_dict_area_recalc_detail_type` (`detail_type`),
  KEY `idx_dict_area_recalc_detail_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料类别面积系数历史重算明细表';

-- ---------------------------
-- 9.12 统一消息通知表（sys_notification）
-- ---------------------------
DROP TABLE IF EXISTS `sys_notification`;
CREATE TABLE `sys_notification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '通知ID',
  `message_id` VARCHAR(50) NOT NULL COMMENT '消息唯一标识 MSG-YYYYMMDD-NNNNN',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `user_id` BIGINT NOT NULL COMMENT '接收人 auth_user.id',
  `category` VARCHAR(30) NOT NULL COMMENT '消息大类: system_notice/food_safety_alert/approval_todo/security_risk/platform_announcement',
  `sub_category` VARCHAR(50) DEFAULT NULL COMMENT '消息子类: alert_dispatch/complaint_dispatch/threshold_alert/material_alert/inventory_alert/equipment_alert',
  `title` VARCHAR(100) NOT NULL COMMENT '消息标题',
  `summary` VARCHAR(300) DEFAULT NULL COMMENT '消息摘要',
  `body` TEXT DEFAULT NULL COMMENT '消息正文',
  `risk_level` VARCHAR(20) NOT NULL DEFAULT 'normal' COMMENT '风险等级: normal/attention/high/severe',
  `read_status` VARCHAR(10) NOT NULL DEFAULT 'unread' COMMENT '阅读状态: unread/read',
  `process_status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '处理状态: pending/processing/processed/closed/invalidated/deleted',
  `source_module` VARCHAR(50) DEFAULT NULL COMMENT '来源模块',
  `related_business_id` BIGINT DEFAULT NULL COMMENT '关联业务ID',
  `related_business_type` VARCHAR(50) DEFAULT NULL COMMENT '关联业务类型',
  `related_org_id` BIGINT DEFAULT NULL COMMENT '关联组织ID',
  `related_warehouse_id` BIGINT DEFAULT NULL COMMENT '关联仓库ID',
  `related_material_id` BIGINT DEFAULT NULL COMMENT '关联物料ID',
  `send_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
  `expiry_time` DATETIME DEFAULT NULL COMMENT '过期时间',
  `push_channels` VARCHAR(200) DEFAULT '["in_app"]' COMMENT '推送渠道',
  `source_snapshot` JSON DEFAULT NULL COMMENT '来源快照',
  `executable_actions` JSON DEFAULT NULL COMMENT '可执行操作',
  `allow_delete` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许删除',
  `org_id` BIGINT DEFAULT NULL COMMENT '所属组织ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_message_id` (`message_id`),
  KEY `idx_notif_user_read` (`user_id`, `read_status`, `deleted`),
  KEY `idx_notif_user_cat` (`user_id`, `category`, `deleted`),
  KEY `idx_notif_business` (`related_business_type`, `related_business_id`),
  KEY `idx_notif_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='统一消息通知表';

-- ---------------------------
-- 9.13 敏感词表（sys_sensitive_word）
-- ---------------------------
DROP TABLE IF EXISTS `sys_sensitive_word`;
CREATE TABLE `sys_sensitive_word` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '敏感词ID',
  `word` VARCHAR(100) NOT NULL COMMENT '敏感词',
  `category` VARCHAR(30) NOT NULL COMMENT '分类：illegal_violation=违法违规，insult_attack=辱骂攻击，privacy_leak=隐私泄露，public_opinion_risk=舆情风险',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active=启用，inactive=停用',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sw_word` (`word`, `tenant_id`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_sw_category` (`category`),
  KEY `idx_sw_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='敏感词表';

-- ---------------------------
-- 9.14 敏感词种子数据
-- ---------------------------
INSERT INTO `sys_sensitive_word` (`word`, `category`, `status`, `tenant_id`) VALUES
-- ==================== 政治相关 (political) ====================
('颠覆国家', 'political', 'active', 1),
('分裂国家', 'political', 'active', 1),
('反党反社', 'political', 'active', 1),
('推翻政权', 'political', 'active', 1),
('煽动颠覆', 'political', 'active', 1),
('国家分裂', 'political', 'active', 1),
('政治迫害', 'political', 'active', 1),
('敌对势力', 'political', 'active', 1),
('境外渗透', 'political', 'active', 1),
('颜色革命', 'political', 'active', 1),
('邪教组织', 'political', 'active', 1),
('法轮功', 'political', 'active', 1),
('法轮大法', 'political', 'active', 1),
('全能神', 'political', 'active', 1),
('呼喊派', 'political', 'active', 1),
('门徒会', 'political', 'active', 1),
('台独', 'political', 'active', 1),
('港独', 'political', 'active', 1),
('藏独', 'political', 'active', 1),

-- ==================== 色情低俗 (pornographic) ====================
('色情服务', 'pornographic', 'active', 1),
('裸聊', 'pornographic', 'active', 1),
('成人视频', 'pornographic', 'active', 1),
('招嫖', 'pornographic', 'active', 1),
('卖淫嫖娼', 'pornographic', 'active', 1),
('约炮', 'pornographic', 'active', 1),
('一夜情', 'pornographic', 'active', 1),
('色情直播', 'pornographic', 'active', 1),
('情趣服务', 'pornographic', 'active', 1),
('援交', 'pornographic', 'active', 1),
('妓女', 'pornographic', 'active', 1),
('嫖娼', 'pornographic', 'active', 1),
('色情网站', 'pornographic', 'active', 1),
('黄色视频', 'pornographic', 'active', 1),
('三级片', 'pornographic', 'active', 1),
('AV女优', 'pornographic', 'active', 1),
('裸体照片', 'pornographic', 'active', 1),
('私密部位', 'pornographic', 'active', 1),
('激情视频', 'pornographic', 'active', 1),

-- ==================== 暴力血腥 (violent) ====================
('杀人方法', 'violent', 'active', 1),
('自制炸弹', 'violent', 'active', 1),
('砍人教程', 'violent', 'active', 1),
('恐怖袭击', 'violent', 'active', 1),
('炸弹制作', 'violent', 'active', 1),
('炸药配方', 'violent', 'active', 1),
('自杀方法', 'violent', 'active', 1),
('教你自杀', 'violent', 'active', 1),
('怎么去死', 'violent', 'active', 1),
('跳楼指南', 'violent', 'active', 1),
('割腕', 'violent', 'active', 1),
('上吊', 'violent', 'active', 1),
('杀人工具', 'violent', 'active', 1),
('灭门', 'violent', 'active', 1),
('碎尸', 'violent', 'active', 1),
('分尸', 'violent', 'active', 1),
('血腥视频', 'violent', 'active', 1),
('暴力视频', 'violent', 'active', 1),
('砍头', 'violent', 'active', 1),
('虐杀', 'violent', 'active', 1),
('活埋', 'violent', 'active', 1),

-- ==================== 违法犯罪 (illegal) ====================
('贩卖毒品', 'illegal', 'active', 1),
('走私军火', 'illegal', 'active', 1),
('洗钱渠道', 'illegal', 'active', 1),
('假钞制作', 'illegal', 'active', 1),
('贩毒', 'illegal', 'active', 1),
('吸毒', 'illegal', 'active', 1),
('冰毒', 'illegal', 'active', 1),
('海洛因', 'illegal', 'active', 1),
('大麻烟', 'illegal', 'active', 1),
('摇头丸', 'illegal', 'active', 1),
('K粉', 'illegal', 'active', 1),
('甲基苯丙胺', 'illegal', 'active', 1),
('假币制作', 'illegal', 'active', 1),
('伪造证件', 'illegal', 'active', 1),
('办假证', 'illegal', 'active', 1),
('黑市交易', 'illegal', 'active', 1),
('地下钱庄', 'illegal', 'active', 1),
('走私香烟', 'illegal', 'active', 1),
('偷渡', 'illegal', 'active', 1),
('偷税漏税', 'illegal', 'active', 1),
('行贿受贿', 'illegal', 'active', 1),
('非法集资', 'illegal', 'active', 1),
('传销组织', 'illegal', 'active', 1),
('网络赌博', 'illegal', 'active', 1),
('赌博网站', 'illegal', 'active', 1),
('赌场', 'illegal', 'active', 1),
('高利贷', 'illegal', 'active', 1),
('暴力催收', 'illegal', 'active', 1),
('黑客攻击', 'illegal', 'active', 1),
('木马病毒', 'illegal', 'active', 1),

-- ==================== 人身攻击/辱骂 (insult_attack) ====================
('蠢猪', 'insult_attack', 'active', 1),
('死垃圾', 'insult_attack', 'active', 1),
('滚去死', 'insult_attack', 'active', 1),
('废物东西', 'insult_attack', 'active', 1),
('傻逼', 'insult_attack', 'active', 1),
('操你', 'insult_attack', 'active', 1),
('妈的', 'insult_attack', 'active', 1),
('去死吧', 'insult_attack', 'active', 1),
('白痴', 'insult_attack', 'active', 1),
('脑残', 'insult_attack', 'active', 1),
('弱智', 'insult_attack', 'active', 1),
('智障', 'insult_attack', 'active', 1),
('死变态', 'insult_attack', 'active', 1),
('混蛋', 'insult_attack', 'active', 1),
('王八蛋', 'insult_attack', 'active', 1),
('狗日的', 'insult_attack', 'active', 1),
('贱人', 'insult_attack', 'active', 1),
('婊子', 'insult_attack', 'active', 1),
('滚蛋', 'insult_attack', 'active', 1),
('闭嘴', 'insult_attack', 'active', 1),
('你大爷', 'insult_attack', 'active', 1),
('神经病', 'insult_attack', 'active', 1),
('二百五', 'insult_attack', 'active', 1),
('猪头', 'insult_attack', 'active', 1),
('畜生', 'insult_attack', 'active', 1),
('人渣', 'insult_attack', 'active', 1),
('败类', 'insult_attack', 'active', 1),
('废物', 'insult_attack', 'active', 1),
('垃圾', 'insult_attack', 'active', 1),

-- ==================== 虚假营销/诈骗 (fraud) ====================
('免费领取红包', 'fraud', 'active', 1),
('点击链接提现', 'fraud', 'active', 1),
('刷单日赚千元', 'fraud', 'active', 1),
('内部稳赚不赔', 'fraud', 'active', 1),
('中奖了', 'fraud', 'active', 1),
('恭喜中奖', 'fraud', 'active', 1),
('领取奖品', 'fraud', 'active', 1),
('免费赠送', 'fraud', 'active', 1),
('兼职刷单', 'fraud', 'active', 1),
('刷信誉', 'fraud', 'active', 1),
('刷好评', 'fraud', 'active', 1),
('代刷销量', 'fraud', 'active', 1),
('高薪兼职', 'fraud', 'active', 1),
('轻松月入过万', 'fraud', 'active', 1),
('零投资创业', 'fraud', 'active', 1),
('快速致富', 'fraud', 'active', 1),
('包赚不赔', 'fraud', 'active', 1),
('内幕消息', 'fraud', 'active', 1),
('庄家操控', 'fraud', 'active', 1),
('股票代操', 'fraud', 'active', 1),
('虚拟币投资', 'fraud', 'active', 1),
('数字货币', 'fraud', 'active', 1),
('传销币', 'fraud', 'active', 1),
('资金盘', 'fraud', 'active', 1),
('杀猪盘', 'fraud', 'active', 1),
('假冒客服', 'fraud', 'active', 1),
('转账汇款', 'fraud', 'active', 1),
('安全账户', 'fraud', 'active', 1),
('验证码发给我', 'fraud', 'active', 1),

-- ==================== 隐私侵权 (privacy_leak) ====================
('身份证号出售', 'privacy_leak', 'active', 1),
('开房记录查询', 'privacy_leak', 'active', 1),
('电话号码贩卖', 'privacy_leak', 'active', 1),
('个人定位追踪', 'privacy_leak', 'active', 1),
('查开房', 'privacy_leak', 'active', 1),
('查人定位', 'privacy_leak', 'active', 1),
('出售个人信息', 'privacy_leak', 'active', 1),
('购买身份证', 'privacy_leak', 'active', 1),
('银行卡号出售', 'privacy_leak', 'active', 1),
('个人征信查询', 'privacy_leak', 'active', 1),
('通话记录查询', 'privacy_leak', 'active', 1),
('微信聊天记录', 'privacy_leak', 'active', 1),
('快递信息贩卖', 'privacy_leak', 'active', 1),
('学生信息出售', 'privacy_leak', 'active', 1),
('车主信息', 'privacy_leak', 'active', 1),
('病患信息', 'privacy_leak', 'active', 1),
('窃听器', 'privacy_leak', 'active', 1),
('偷拍设备', 'privacy_leak', 'active', 1),
('针孔摄像头', 'privacy_leak', 'active', 1),
('定位器', 'privacy_leak', 'active', 1),

-- ==================== 宗教极端 (religious_extremism) ====================
('圣战', 'religious_extremism', 'active', 1),
('极端主义', 'religious_extremism', 'active', 1),
('恐怖组织', 'religious_extremism', 'active', 1),
('基地组织', 'religious_extremism', 'active', 1),
('塔利班', 'religious_extremism', 'active', 1),
('ISIS', 'religious_extremism', 'active', 1),
('达伊沙', 'religious_extremism', 'active', 1),
('极端分子', 'religious_extremism', 'active', 1),
('殉教', 'religious_extremism', 'active', 1),
('人体炸弹', 'religious_extremism', 'active', 1),
('自杀式袭击', 'religious_extremism', 'active', 1),
('异教徒', 'religious_extremism', 'active', 1),

-- ==================== 舆情风险 (public_opinion_risk) ====================
('集体罢工', 'public_opinion_risk', 'active', 1),
('聚众闹事', 'public_opinion_risk', 'active', 1),
('食物中毒死了人', 'public_opinion_risk', 'active', 1),
('吃出老鼠头', 'public_opinion_risk', 'active', 1),
('集体食物中毒', 'public_opinion_risk', 'active', 1),
('集体维权', 'public_opinion_risk', 'active', 1),
('群体性事件', 'public_opinion_risk', 'active', 1),
('游行示威', 'public_opinion_risk', 'active', 1),
('上访', 'public_opinion_risk', 'active', 1),
('静坐抗议', 'public_opinion_risk', 'active', 1),
('拉横幅', 'public_opinion_risk', 'active', 1),
('堵门抗议', 'public_opinion_risk', 'active', 1),
('黑心商家', 'public_opinion_risk', 'active', 1),
('黑心企业', 'public_opinion_risk', 'active', 1),
('毒食品', 'public_opinion_risk', 'active', 1),
('地沟油', 'public_opinion_risk', 'active', 1),
('苏丹红', 'public_opinion_risk', 'active', 1),
('三聚氰胺', 'public_opinion_risk', 'active', 1),
('瘦肉精', 'public_opinion_risk', 'active', 1),
('塑化剂', 'public_opinion_risk', 'active', 1),
('甲醛超标', 'public_opinion_risk', 'active', 1),
('吃了死人', 'public_opinion_risk', 'active', 1),
('食物里有虫', 'public_opinion_risk', 'active', 1),
('吃出异物', 'public_opinion_risk', 'active', 1),
('以次充好', 'public_opinion_risk', 'active', 1),
('虚假宣传', 'public_opinion_risk', 'active', 1),
('食品安全事故', 'public_opinion_risk', 'active', 1),
('过期食品', 'public_opinion_risk', 'active', 1);

-- ---------------------------
-- 9.15 第三方接入平台模板表（sys_integration_provider_template）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_provider_template`;
CREATE TABLE `sys_integration_provider_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `provider_code` VARCHAR(100) NOT NULL COMMENT '平台编码',
  `provider_name` VARCHAR(100) NOT NULL COMMENT '平台名称',
  `provider_type` VARCHAR(50) NOT NULL COMMENT '平台类型',
  `auth_type` VARCHAR(50) NOT NULL COMMENT '鉴权类型',
  `protocol_type` VARCHAR(50) NOT NULL COMMENT '协议类型',
  `callback_supported` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持回调',
  `file_pull_supported` TINYINT NOT NULL DEFAULT 0 COMMENT '是否支持文件拉取',
  `scene_codes` JSON DEFAULT NULL COMMENT '支持场景编码列表',
  `request_template` JSON DEFAULT NULL COMMENT '请求模板',
  `response_template` JSON DEFAULT NULL COMMENT '响应模板',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态：active/inactive',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `org_id` BIGINT NOT NULL DEFAULT 0 COMMENT '所属组织ID，平台模板固定为0',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_integration_provider_code` (`tenant_id`, `provider_code`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_integration_provider_type` (`provider_type`),
  KEY `idx_integration_provider_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方接入平台模板表';

-- ---------------------------
-- 9.16 第三方模块接入配置表（sys_integration_module_config）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_module_config`;
CREATE TABLE `sys_integration_module_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `biz_module` VARCHAR(100) NOT NULL COMMENT '业务模块',
  `biz_scene` VARCHAR(100) NOT NULL COMMENT '业务子场景',
  `provider_code` VARCHAR(100) NOT NULL COMMENT '平台编码',
  `config_name` VARCHAR(200) NOT NULL COMMENT '配置名称',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  `default_mode` VARCHAR(30) NOT NULL DEFAULT 'manual' COMMENT '默认维护方式：manual/third_party',
  `allow_document_switch` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许单据级切换',
  `force_third_party` TINYINT NOT NULL DEFAULT 0 COMMENT '是否强制第三方',
  `trigger_strategy` VARCHAR(30) NOT NULL DEFAULT 'manual' COMMENT '触发策略：manual/scheduler/callback',
  `allow_manual_fallback` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许手工兜底',
  `auto_cover_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否自动覆盖',
  `auto_cover_strategy` VARCHAR(30) DEFAULT 'merge' COMMENT '自动覆盖策略：merge/overwrite',
  `allow_manual_confirm_cover` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许人工确认后覆盖',
  `attachment_pull_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否拉取附件',
  `callback_enabled` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用回调',
  `callback_url` VARCHAR(500) DEFAULT NULL COMMENT '回调地址',
  `external_no_field_rule` VARCHAR(200) DEFAULT NULL COMMENT '外部单号取值规则',
  `access_token_url` VARCHAR(500) DEFAULT NULL COMMENT 'AccessToken获取地址',
  `refresh_token_url` VARCHAR(500) DEFAULT NULL COMMENT 'RefreshToken获取地址',
  `token_request_method` VARCHAR(20) DEFAULT 'POST' COMMENT 'Token请求方式',
  `sync_frequency_minutes` INT DEFAULT 60 COMMENT '同步频率（分钟）',
  `schedule_cron` VARCHAR(100) DEFAULT NULL COMMENT '定时Cron表达式',
  `timeout_ms` BIGINT DEFAULT 10000 COMMENT '超时毫秒数',
  `retry_max_count` INT DEFAULT 3 COMMENT '最大重试次数',
  `last_sync_at` DATETIME DEFAULT NULL COMMENT '最近同步时间',
  `last_sync_status` VARCHAR(20) DEFAULT NULL COMMENT '最近同步状态',
  `last_error_message` VARCHAR(1000) DEFAULT NULL COMMENT '最近错误信息',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_integration_module_config` (`tenant_id`, `org_id`, `biz_module`, `biz_scene`, `provider_code`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_integration_module_config_org` (`org_id`),
  KEY `idx_integration_module_config_scene` (`biz_module`, `biz_scene`),
  KEY `idx_integration_module_config_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方模块接入配置表';

-- ---------------------------
-- 9.17 第三方接入密钥配置表（sys_integration_secret_config）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_secret_config`;
CREATE TABLE `sys_integration_secret_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_id` BIGINT NOT NULL COMMENT '配置ID',
  `secret_key` VARCHAR(100) NOT NULL COMMENT '密钥参数名',
  `secret_value` VARCHAR(1000) DEFAULT NULL COMMENT '密钥参数值（加密）',
  `secret_mask` VARCHAR(255) DEFAULT NULL COMMENT '密钥脱敏值',
  `encrypted_flag` TINYINT NOT NULL DEFAULT 1 COMMENT '是否加密',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_integration_secret_config` (`config_id`, `secret_key`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_integration_secret_org` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方接入密钥配置表';

-- ---------------------------
-- 9.18 第三方字段映射表（sys_integration_field_mapping）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_field_mapping`;
CREATE TABLE `sys_integration_field_mapping` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_id` BIGINT NOT NULL COMMENT '配置ID',
  `source_field` VARCHAR(100) DEFAULT NULL COMMENT '第三方字段名',
  `source_path` VARCHAR(255) DEFAULT NULL COMMENT '第三方JSON路径',
  `target_field` VARCHAR(100) NOT NULL COMMENT '系统字段名',
  `transform_type` VARCHAR(50) NOT NULL COMMENT '转换规则类型',
  `transform_rule` VARCHAR(1000) DEFAULT NULL COMMENT '转换规则表达式',
  `default_value` VARCHAR(255) DEFAULT NULL COMMENT '默认值',
  `required_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否必填',
  `sort_no` INT NOT NULL DEFAULT 1 COMMENT '排序号',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  `error_strategy` VARCHAR(30) NOT NULL DEFAULT 'fail' COMMENT '异常时处理方式：fail/skip/log_only/manual_review',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_integration_field_mapping_config` (`config_id`),
  KEY `idx_integration_field_mapping_target` (`target_field`),
  UNIQUE KEY `uk_integration_field_mapping_enabled` (`tenant_id`, `config_id`, `target_field`, (CASE WHEN deleted = 0 AND enabled = 1 THEN 1 ELSE NULL END))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方字段映射表';

-- ---------------------------
-- 9.19 第三方状态映射表（sys_integration_status_mapping）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_status_mapping`;
CREATE TABLE `sys_integration_status_mapping` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_id` BIGINT NOT NULL COMMENT '配置ID',
  `source_status_code` VARCHAR(100) NOT NULL COMMENT '第三方状态编码',
  `source_status_name` VARCHAR(100) DEFAULT NULL COMMENT '第三方状态名称',
  `target_status_code` VARCHAR(100) NOT NULL COMMENT '系统标准状态编码',
  `finish_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否结束同步',
  `trigger_business_action` TINYINT NOT NULL DEFAULT 0 COMMENT '是否触发业务动作',
  `action_code` VARCHAR(100) DEFAULT NULL COMMENT '业务动作编码',
  `write_attachment_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否写入附件',
  `sort_no` INT NOT NULL DEFAULT 1 COMMENT '排序号',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_integration_status_mapping_config` (`config_id`),
  KEY `idx_integration_status_mapping_target` (`target_status_code`),
  UNIQUE KEY `uk_integration_status_mapping_source` (`tenant_id`, `config_id`, `source_status_code`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方状态映射表';

-- ---------------------------
-- 9.20 第三方单据绑定表（sys_integration_binding）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_binding`;
CREATE TABLE `sys_integration_binding` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_id` BIGINT NOT NULL COMMENT '配置ID',
  `provider_code` VARCHAR(100) NOT NULL COMMENT '平台编码',
  `biz_module` VARCHAR(100) NOT NULL COMMENT '业务模块',
  `biz_scene` VARCHAR(100) NOT NULL COMMENT '业务场景',
  `biz_id` BIGINT NOT NULL COMMENT '业务主键ID',
  `biz_no` VARCHAR(100) NOT NULL COMMENT '业务编号',
  `external_no` VARCHAR(100) DEFAULT NULL COMMENT '第三方外部编号',
  `maintenance_mode` VARCHAR(30) NOT NULL DEFAULT 'manual' COMMENT '维护方式：manual/third_party',
  `mode_source` VARCHAR(30) NOT NULL DEFAULT 'user_selected' COMMENT '方式来源：defaulted/user_selected/forced',
  `mode_locked` TINYINT NOT NULL DEFAULT 0 COMMENT '是否锁定维护方式',
  `sync_status` VARCHAR(30) DEFAULT NULL COMMENT '同步状态：pending/running/success/failed/no_data/mapping_missing',
  `first_bind_at` DATETIME DEFAULT NULL COMMENT '首次绑定时间',
  `last_sync_at` DATETIME DEFAULT NULL COMMENT '最近同步时间',
  `next_sync_at` DATETIME DEFAULT NULL COMMENT '下次计划同步时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_integration_binding_unique` (`tenant_id`, `config_id`, `biz_scene`, `biz_id`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_integration_binding_external` (`provider_code`, `external_no`),
  KEY `idx_integration_binding_biz` (`biz_module`, `biz_scene`, `biz_id`),
  KEY `idx_integration_binding_org` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方单据绑定表';

-- ---------------------------
-- 9.21 第三方同步任务表（sys_integration_sync_task）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_sync_task`;
CREATE TABLE `sys_integration_sync_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_no` VARCHAR(100) NOT NULL COMMENT '任务编号',
  `binding_id` BIGINT NOT NULL COMMENT '绑定ID',
  `config_id` BIGINT NOT NULL COMMENT '配置ID',
  `task_type` VARCHAR(50) NOT NULL COMMENT '任务类型：sync/query_only/retry/callback_followup',
  `trigger_type` VARCHAR(50) NOT NULL COMMENT '触发类型：manual/scheduler/callback',
  `task_status` VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT '任务状态：pending/running/success/failed/no_data/mapping_missing',
  `plan_execute_at` DATETIME DEFAULT NULL COMMENT '计划执行时间',
  `start_at` DATETIME DEFAULT NULL COMMENT '开始执行时间',
  `finish_at` DATETIME DEFAULT NULL COMMENT '结束执行时间',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `operator_id` BIGINT DEFAULT NULL COMMENT '触发人ID',
  `operator_name` VARCHAR(100) DEFAULT NULL COMMENT '触发人名称',
  `biz_id` BIGINT NOT NULL COMMENT '业务主键ID',
  `biz_no` VARCHAR(100) NOT NULL COMMENT '业务编号',
  `biz_module` VARCHAR(100) NOT NULL COMMENT '业务模块',
  `biz_scene` VARCHAR(100) NOT NULL COMMENT '业务场景',
  `external_no` VARCHAR(100) DEFAULT NULL COMMENT '第三方外部编号',
  `result_message` VARCHAR(1000) DEFAULT NULL COMMENT '结果说明',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_integration_sync_task_no` (`task_no`, (CASE WHEN deleted = 0 THEN 0 ELSE NULL END)),
  KEY `idx_integration_sync_task_binding` (`binding_id`),
  KEY `idx_integration_sync_task_config` (`config_id`),
  KEY `idx_integration_sync_task_status` (`task_status`),
  KEY `idx_integration_sync_task_org` (`org_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方同步任务表';

-- ---------------------------
-- 9.22 第三方同步日志表（sys_integration_sync_log）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_sync_log`;
CREATE TABLE `sys_integration_sync_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_id` BIGINT DEFAULT NULL COMMENT '任务ID',
  `binding_id` BIGINT DEFAULT NULL COMMENT '绑定ID',
  `config_id` BIGINT NOT NULL COMMENT '配置ID',
  `config_name_snapshot` VARCHAR(200) DEFAULT NULL COMMENT '执行当时的配置名称快照',
  `provider_code` VARCHAR(100) NOT NULL COMMENT '平台编码',
  `provider_name_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '执行当时的平台名称快照',
  `biz_id` BIGINT NOT NULL COMMENT '业务主键ID',
  `biz_no` VARCHAR(100) NOT NULL COMMENT '业务编号',
  `biz_module` VARCHAR(100) NOT NULL COMMENT '业务模块',
  `biz_scene` VARCHAR(100) NOT NULL COMMENT '业务场景',
  `external_no` VARCHAR(100) DEFAULT NULL COMMENT '第三方外部编号',
  `task_type` VARCHAR(50) DEFAULT NULL COMMENT '任务类型',
  `request_payload` JSON DEFAULT NULL COMMENT '请求报文',
  `request_headers` JSON DEFAULT NULL COMMENT '请求头快照',
  `request_body` JSON DEFAULT NULL COMMENT '请求体快照',
  `response_payload` JSON DEFAULT NULL COMMENT '响应报文',
  `normalized_payload` JSON DEFAULT NULL COMMENT '标准化结果',
  `sync_status` VARCHAR(30) NOT NULL COMMENT '同步状态：success/failed/no_data/mapping_missing',
  `error_code` VARCHAR(100) DEFAULT NULL COMMENT '错误码',
  `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
  `duration_ms` BIGINT DEFAULT NULL COMMENT '耗时毫秒数',
  `audit_log_id` BIGINT DEFAULT NULL COMMENT '关联审计日志ID',
  `result_message` VARCHAR(1000) DEFAULT NULL COMMENT '结果说明',
  `write_back_result` VARCHAR(1000) DEFAULT NULL COMMENT '业务回写结果说明',
  `trigger_type` VARCHAR(50) DEFAULT NULL COMMENT '触发类型',
  `operator_id` BIGINT DEFAULT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(100) DEFAULT NULL COMMENT '操作人名称',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `org_name_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '执行当时的组织名称快照',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `handle_status` VARCHAR(50) DEFAULT NULL COMMENT '人工处理闭环状态：pending_review/confirmed/ignored/rechecked',
  `handled_by` BIGINT DEFAULT NULL COMMENT '最近处理人ID',
  `handled_by_name` VARCHAR(100) DEFAULT NULL COMMENT '最近处理人名称',
  `handled_at` DATETIME DEFAULT NULL COMMENT '最近处理时间',
  `handle_remark` VARCHAR(500) DEFAULT NULL COMMENT '人工处理备注',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_integration_sync_log_task` (`task_id`),
  KEY `idx_integration_sync_log_config` (`config_id`),
  KEY `idx_integration_sync_log_status` (`sync_status`),
  KEY `idx_integration_sync_log_org` (`org_id`),
  KEY `idx_integration_sync_log_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方同步日志表';

-- ---------------------------
-- 9.23 第三方回调日志表（sys_integration_callback_log）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_callback_log`;
CREATE TABLE `sys_integration_callback_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `binding_id` BIGINT DEFAULT NULL COMMENT '绑定ID',
  `config_id` BIGINT DEFAULT NULL COMMENT '接入配置ID',
  `config_name_snapshot` VARCHAR(200) DEFAULT NULL COMMENT '执行当时的配置名称快照',
  `provider_code` VARCHAR(100) NOT NULL COMMENT '平台编码',
  `provider_name_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '执行当时的平台名称快照',
  `callback_uri` VARCHAR(500) DEFAULT NULL COMMENT '回调地址',
  `callback_headers` JSON DEFAULT NULL COMMENT '回调请求头',
  `callback_payload` JSON DEFAULT NULL COMMENT '回调请求体',
  `client_ip` VARCHAR(100) DEFAULT NULL COMMENT '来源IP',
  `sign_result` VARCHAR(20) DEFAULT NULL COMMENT '验签结果：pass/fail',
  `idempotent_key` VARCHAR(255) DEFAULT NULL COMMENT '幂等键',
  `claim_key` VARCHAR(255) DEFAULT NULL COMMENT '幂等占坑键',
  `process_status` VARCHAR(30) DEFAULT NULL COMMENT '处理状态：pending/security_failed/ignored/duplicate/success/failed/no_data/mapping_missing',
  `process_result` VARCHAR(1000) DEFAULT NULL COMMENT '处理结果',
  `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
  `biz_id` BIGINT DEFAULT NULL COMMENT '业务主键ID',
  `biz_no` VARCHAR(100) DEFAULT NULL COMMENT '业务编号',
  `biz_module` VARCHAR(100) DEFAULT NULL COMMENT '业务模块',
  `biz_scene` VARCHAR(100) DEFAULT NULL COMMENT '业务场景',
  `external_no` VARCHAR(100) DEFAULT NULL COMMENT '第三方外部编号',
  `task_id` BIGINT DEFAULT NULL COMMENT '关联同步任务ID',
  `sync_log_id` BIGINT DEFAULT NULL COMMENT '关联同步日志ID',
  `audit_log_id` BIGINT DEFAULT NULL COMMENT '关联审计日志ID',
  `org_id` BIGINT DEFAULT NULL COMMENT '所属组织ID',
  `org_name_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '执行当时的组织名称快照',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_integration_callback_provider` (`provider_code`),
  KEY `idx_integration_callback_binding` (`binding_id`),
  KEY `idx_integration_callback_config` (`config_id`),
  KEY `idx_integration_callback_idempotent` (`idempotent_key`),
  UNIQUE KEY `uk_integration_callback_claim_key` (`claim_key`),
  KEY `idx_integration_callback_task` (`task_id`),
  KEY `idx_integration_callback_sync_log` (`sync_log_id`),
  KEY `idx_integration_callback_org` (`org_id`),
  KEY `idx_integration_callback_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方回调日志表';

-- ---------------------------
-- 9.24 第三方附件转存记录表（sys_integration_file_record）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_file_record`;
CREATE TABLE `sys_integration_file_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `binding_id` BIGINT DEFAULT NULL COMMENT '绑定ID',
  `config_id` BIGINT DEFAULT NULL COMMENT '接入配置ID',
  `config_name_snapshot` VARCHAR(200) DEFAULT NULL COMMENT '执行当时的配置名称快照',
  `biz_module` VARCHAR(100) NOT NULL COMMENT '业务模块',
  `biz_scene` VARCHAR(100) NOT NULL COMMENT '业务场景',
  `biz_id` BIGINT DEFAULT NULL COMMENT '业务主键ID',
  `biz_no` VARCHAR(100) DEFAULT NULL COMMENT '业务编号',
  `provider_code` VARCHAR(100) NOT NULL COMMENT '平台编码',
  `provider_name_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '执行当时的平台名称快照',
  `source_file_name` VARCHAR(255) DEFAULT NULL COMMENT '原文件名',
  `source_file_url` VARCHAR(1000) DEFAULT NULL COMMENT '脱敏后的原文件地址',
  `source_url_signature` VARCHAR(128) DEFAULT NULL COMMENT '原文件地址签名',
  `minio_file_url` VARCHAR(1000) DEFAULT NULL COMMENT 'MinIO文件地址',
  `file_hash` VARCHAR(128) DEFAULT NULL COMMENT '文件摘要',
  `file_size` VARCHAR(50) DEFAULT NULL COMMENT '文件大小',
  `mime_type` VARCHAR(100) DEFAULT NULL COMMENT '文件MIME类型',
  `download_status` VARCHAR(30) DEFAULT NULL COMMENT '下载状态：pending/success/failed/skipped/reused',
  `storage_status` VARCHAR(30) DEFAULT NULL COMMENT '转存状态：pending/success/failed/skipped/reused',
  `error_code` VARCHAR(100) DEFAULT NULL COMMENT '失败错误码',
  `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '失败错误信息',
  `task_id` BIGINT DEFAULT NULL COMMENT '关联同步任务ID',
  `sync_log_id` BIGINT DEFAULT NULL COMMENT '关联同步日志ID',
  `audit_log_id` BIGINT DEFAULT NULL COMMENT '关联审计日志ID',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `org_name_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '执行当时的组织名称快照',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_integration_file_binding` (`binding_id`),
  KEY `idx_integration_file_config` (`config_id`),
  KEY `idx_integration_file_provider` (`provider_code`),
  KEY `idx_integration_file_task` (`task_id`),
  KEY `idx_integration_file_sync_log` (`sync_log_id`),
  KEY `idx_integration_file_org` (`org_id`),
  KEY `idx_integration_file_biz_no` (`biz_no`),
  KEY `idx_integration_file_created` (`created_at`),
  KEY `idx_integration_file_updated` (`updated_at`),
  UNIQUE KEY `uk_integration_file_binding_signature` (`binding_id`, `source_url_signature`, `tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方附件转存记录表';

-- ---------------------------
-- 9.22 第三方健康检查测试日志表（sys_integration_health_check_log）
-- ---------------------------
DROP TABLE IF EXISTS `sys_integration_health_check_log`;
CREATE TABLE `sys_integration_health_check_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_id` BIGINT NOT NULL COMMENT '接入配置ID',
  `config_name_snapshot` VARCHAR(200) DEFAULT NULL COMMENT '测试当时的配置名称快照',
  `biz_module` VARCHAR(100) NOT NULL COMMENT '业务模块',
  `biz_scene` VARCHAR(100) NOT NULL COMMENT '业务场景',
  `provider_code` VARCHAR(100) NOT NULL COMMENT '平台编码',
  `provider_name_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '测试当时的平台名称快照',
  `test_status` VARCHAR(30) NOT NULL COMMENT '测试状态：success/warning/failed',
  `auth_success` TINYINT DEFAULT NULL COMMENT '鉴权是否成功：1成功/0失败',
  `reachable` TINYINT DEFAULT NULL COMMENT '第三方接口是否可达：1成功/0失败',
  `callback_reachable` TINYINT DEFAULT NULL COMMENT '回调地址是否可达：1成功/0失败',
  `auth_message` VARCHAR(1000) DEFAULT NULL COMMENT '鉴权说明',
  `reachability_message` VARCHAR(1000) DEFAULT NULL COMMENT '接口连通性说明',
  `callback_message` VARCHAR(1000) DEFAULT NULL COMMENT '回调连通性说明',
  `test_message` VARCHAR(1000) DEFAULT NULL COMMENT '测试结果汇总',
  `error_code` VARCHAR(100) DEFAULT NULL COMMENT '错误码',
  `error_message` VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
  `request_payload` LONGTEXT DEFAULT NULL COMMENT '请求报文快照',
  `request_headers` LONGTEXT DEFAULT NULL COMMENT '请求头快照',
  `request_body` LONGTEXT DEFAULT NULL COMMENT '请求体快照',
  `response_payload` LONGTEXT DEFAULT NULL COMMENT '响应报文快照',
  `operator_id` BIGINT DEFAULT NULL COMMENT '测试人ID',
  `operator_name` VARCHAR(100) DEFAULT NULL COMMENT '测试人名称',
  `org_id` BIGINT NOT NULL COMMENT '所属组织ID',
  `org_name_snapshot` VARCHAR(100) DEFAULT NULL COMMENT '测试当时的组织名称快照',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户ID',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_integration_health_config` (`config_id`),
  KEY `idx_integration_health_provider` (`provider_code`),
  KEY `idx_integration_health_org` (`org_id`),
  KEY `idx_integration_health_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='第三方健康检查测试日志表';

-- ============================================================
-- 初始化完成
-- ============================================================
